/**
 * Question Data for Consultant Feature
 * Contains exactly 8 themes and 100 UNIQUE questions for each.
 * All mechanical variations and suffixes like "(Chiêm nghiệm sâu)" have been removed.
 */

const THEMES = [
    { id: 'career', name: 'Công danh', icon: '🏛️' },
    { id: 'love', name: 'Tình duyên', icon: '❤️' },
    { id: 'wealth', name: 'Tài lộc', icon: '💰' },
    { id: 'health', name: 'Sức khỏe', icon: '🏥' },
    { id: 'children', name: 'Con cái', icon: '👶' },
    { id: 'colleagues', name: 'Đồng nghiệp', icon: '👥' },
    { id: 'partnership', name: 'Hợp tác', icon: '🤝' },
    { id: 'misfortune', name: 'Tai họa', icon: '🌪️' }
];

const QUESTIONS_DATA = {
    career: [
        { text: "Sự nghiệp của tôi phù hợp với đi làm thuê hay làm chủ?", logic: 'CAREER_TYPE_OFFICE_VS_BIZ' },
        { text: "Khi nào là thời điểm tốt nhất để tôi chuyển việc?", logic: 'CAREER_TIMING_TRANSITION' },
        { text: "Tôi có quý nhân giúp đỡ trong sự nghiệp không?", logic: 'CAREER_NOBLE_STARS' },
        { text: "Công việc hiện tại có giúp tôi thăng tiến trong 3 năm tới không?", logic: 'CAREER_PROMOTION_3Y' },
        { text: "Tôi nên chọn ngành nghề thuộc hành nào thì đại cát?", logic: 'CAREER_SECTOR_ELEMENT' },
        { text: "Sự nghiệp của tôi vượng nhất vào đại vận nào?", logic: 'CAREER_LUCK_CYCLE_PEAK' },
        { text: "Tôi có hợp với việc đi làm xa xứ (xuất ngoại) không?", logic: 'CAREER_LOCATION_TRAVEL' },
        { text: "Nhật chủ của tôi mang tính cách gì ảnh hưởng đến công danh?", logic: 'CAREER_PERSONALITY_IMPACT' },
        { text: "Tôi có duyên với các công việc liên quan đến nghệ thuật không?", logic: 'CAREER_SECTOR_ART' },
        { text: "Lá số của tôi có cách cục 'Quan Ấn Tương Sinh' không?", logic: 'CAREER_SPECIFIC_GEJU' },
        { text: "Tôi nên làm việc trong môi trường nhà nước hay tư nhân?", logic: 'CAREER_ENVIRO_GOV_VS_PVT' },
        { text: "Làm sao để hóa giải Kiếp Tài đang cản trở sự nghiệp?", logic: 'CAREER_HURDLE_ROB_WEALTH' },
        { text: "Tại sao công việc của tôi thường gặp thị phi?", logic: 'CAREER_HURDLE_GOSSIP' },
        { text: "Tôi có số làm lãnh đạo cấp cao không?", logic: 'CAREER_BOSS_POTENTIAL' },
        { text: "Tài năng của tôi thường bị che khuất bởi yếu tố nào?", logic: 'CAREER_HURDLE_HIDDEN' },
        { text: "Thập thần nào đang đóng vai trò Dụng thần trong sự nghiệp?", logic: 'CAREER_DUNG_THAN' },
        { text: "Tôi có thích hợp với công việc kinh doanh bất động sản không?", logic: 'CAREER_SECTOR_EARTH' },
        { text: "Đường công danh của tôi sau tuổi 40 sẽ như thế nào?", logic: 'CAREER_AGE_40_PLUS' },
        { text: "Tôi có nên học thêm văn bằng 2 để đổi vận không?", logic: 'CAREER_LEARNING_UPGRADE' },
        { text: "Sự nghiệp của tôi có được hưởng phúc đức từ tổ tiên không?", logic: 'CAREER_ANCESTOR_BLESS' },
        { text: "Lá số có dấu hiệu của việc 'Tài đa thân nhược' cản trở công danh không?", logic: 'CAREER_HURDLE_WEAK_TREAT' },
        { text: "Tôi có nên khởi nghiệp cùng bạn bè hay đơn độc?", logic: 'CAREER_PARTNER_STARTUP' },
        { text: "Làm sao để khơi dậy năng lực lãnh đạo tiềm ẩn?", logic: 'CAREER_BOSS_AWAKEN' },
        { text: "Vận trình công danh năm nay có biến động gì lớn?", logic: 'CAREER_YEARLY_CHANGE' },
        { text: "Tôi có duyên với ngành công nghệ thông tin không?", logic: 'CAREER_SECTOR_TECH' },
        { text: "Sự nghiệp của tôi có bị ảnh hưởng bởi vận hạn của người thân không?", logic: 'CAREER_FAMILY_IMPACT' },
        { text: "Tôi nên làm gì khi gặp sao 'Tuế Phá' chiếu vào cung công danh?", logic: 'CAREER_HURDLE_TUE_PHA' },
        { text: "Lá số có 'Mã Tinh' chủ về sự di chuyển trong công việc không?", logic: 'CAREER_LOCATION_MOVE' },
        { text: "Tôi có số làm thầy (giáo viên, diễn giả) không?", logic: 'CAREER_SECTOR_TEACHER' },
        { text: "Làm sao để thu hút cơ hội thăng tiến bất ngờ?", logic: 'CAREER_PROMOTION_LUCK' },
        { text: "Tôi nên làm gì để tăng cường sự tập trung trong công việc?", logic: 'CAREER_ACTION_FOCUS' },
        { text: "Nghề nghiệp nào giúp tôi phát huy tối đa 'Thiên Ấn'?", logic: 'CAREER_SECTOR_INNOVATION' },
        { text: "Tôi có số làm trong ngành luật hay tư pháp không?", logic: 'CAREER_SECTOR_LAW' },
        { text: "Làm sao để biết mình đã đạt đỉnh cao sự nghiệp chưa?", logic: 'CAREER_SIGNS_PEAK' },
        { text: "Tôi có nên đổi tên để sự nghiệp thuận lợi hơn không?", logic: 'CAREER_ACTION_RENAME' },
        { text: "Đâu là yếu tố phong thủy quan trọng nhất cho văn phòng của tôi?", logic: 'CAREER_FENGSHUI_OFFICE' },
        { text: "Tôi có duyên với ngành y hay dược phẩm không?", logic: 'CAREER_SECTOR_MEDICAL' },
        { text: "Làm sao để vượt qua sự trì trệ trong vận trình công danh?", logic: 'CAREER_HURDLE_STAGNATION' },
        { text: "Tôi nên chọn sếp mang hành gì để được nâng đỡ?", logic: 'CAREER_BOSS_ELEMENT' },
        { text: "Công danh của tôi có phát triển tốt ở miền Nam không?", logic: 'CAREER_LOCATION_SOUTH' },
        { text: "Tôi có năng khiếu trong việc quản lý tài chính doanh nghiệp không?", logic: 'CAREER_SECTOR_FINANCE' },
        { text: "Tại sao tôi nỗ lực nhiều nhưng kết quả chưa như ý?", logic: 'CAREER_HURDLE_EFFORT_VS_RESULT' },
        { text: "Tôi có nên quay lại trường học để nghiên cứu chuyên sâu?", logic: 'CAREER_ACTION_RESEARCH' },
        { text: "Mối quan hệ nào là then chốt cho sự thăng tiến của tôi?", logic: 'CAREER_NOBLE_LEVEL' },
        { text: "Tôi có số làm trong ngành truyền thông, giải trí không?", logic: 'CAREER_SECTOR_MEDIA' },
        { text: "Làm sao để hóa giải sự cạnh tranh gay gắt từ đồng nghiệp?", logic: 'CAREER_HURDLE_COMPETITION' },
        { text: "Tôi nên bắt đầu dự án lớn vào tháng mấy trong năm?", logic: 'CAREER_TIMING_MONTH' },
        { text: "Lá số có 'Hoa Cái' chủ về tài năng nghệ thuật độc đáo không?", logic: 'CAREER_STARS_HOA_CAI' },
        { text: "Tôi có phù hợp với công việc làm việc tự do (Freelance)?", logic: 'CAREER_TYPE_FREELANCE' },
        { text: "Làm sao để xây dựng thương hiệu cá nhân theo Bát tự?", logic: 'CAREER_ACTION_BRANDING' },
        { text: "Sự nghiệp của tôi có liên quan đến việc viết lách không?", logic: 'CAREER_SECTOR_WRITING' },
        { text: "Tôi có nên tham gia vào các khóa đào tạo kỹ năng lãnh đạo?", logic: 'CAREER_ACTION_TRAINING' },
        { text: "Vận trình sự nghiệp của tôi qua 12 cung Trường sinh như thế nào?", logic: 'CAREER_NATURE_12_CYCLES' },
        { text: "Tôi có số đổi nghề giữa chừng không?", logic: 'CAREER_TYPE_PIVOT' },
        { text: "Làm sao để thu hút vốn đầu tư cho ý tưởng khởi nghiệp?", logic: 'CAREER_ACTION_FUNDING' },
        { text: "Tôi nên làm việc ở tầng cao hay tầng thấp để vượng khí?", logic: 'CAREER_FENGSHUI_HEIGHT' },
        { text: "Tôi có duyên với các công việc liên quan đến vận tải, logistics không?", logic: 'CAREER_SECTOR_LOGISTICS' },
        { text: "Tại sao tôi cảm thấy không hạnh phúc với công việc hiện tại?", logic: 'CAREER_PSYCHOLOGY' },
        { text: "Tôi có nên mở rộng kinh doanh sang lĩnh vực mới?", logic: 'CAREER_ACTION_EXPAND' },
        { text: "Lá số có 'Thiên Mã' báo hiệu sự thành công nhờ đi xa không?", logic: 'CAREER_STARS_THIEN_MA' },
        { text: "Tôi có năng lực giải quyết khủng hoảng doanh nghiệp không?", logic: 'CAREER_BOSS_CRISIS' },
        { text: "Tôi nên chọn cộng sự mang hành gì để bù đắp khuyết điểm?", logic: 'CAREER_PARTNER_ELEMENT' },
        { text: "Sự nghiệp của tôi có được hưởng lợi từ sự phát triển của công nghệ?", logic: 'CAREER_ENV_TECH' },
        { text: "Làm sao để biết đâu là cơ hội thực sự thay vì ảo ảnh?", logic: 'CAREER_SIGNS_OPPORTUNITY' },
        { text: "Tôi có số làm trong ngành dịch vụ khách hàng không?", logic: 'CAREER_SECTOR_SERVICE' },
        { text: "Vận trình công danh năm sau có tốt hơn năm nay không?", logic: 'CAREER_YEARLY_NEXT' },
        { text: "Tôi nên làm gì để tạo ấn tượng tốt với hội đồng quản trị?", logic: 'CAREER_ACTION_BOARD' },
        { text: "Tôi có duyên với công việc thiết kế, sáng tạo không?", logic: 'CAREER_SECTOR_DESIGN' },
        { text: "Làm sao để cân bằng giữa tham vọng và sự an lạc?", logic: 'CAREER_ACTION_BALANCE' },
        { text: "Tôi có nên làm việc cho các tập đoàn đa quốc gia?", logic: 'CAREER_TYPE_MNC' },
        { text: "Lá số có 'Kim Dư' chủ về sự giàu sang nhờ công danh không?", logic: 'CAREER_STARS_KIM_DU' },
        { text: "Tôi có năng khiếu trong việc đàm phán, thương thảo không?", logic: 'CAREER_BOSS_NEGOTIATE' },
        { text: "Tôi nên sử dụng màu sắc gì cho danh thiếp để kích vận?", logic: 'CAREER_FENGSHUI_CARD' },
        { text: "Tôi có duyên với ngành tư vấn định hướng, coaching không?", logic: 'CAREER_SECTOR_COACHING' },
        { text: "Tại sao tôi thường gặp khó khăn ở giai đoạn đầu của dự án?", logic: 'CAREER_HURDLE_STARTUP' },
        { text: "Tôi có nên tham gia vào các hoạt động chính trị, đoàn thể?", logic: 'CAREER_ACTION_POLITIC' },
        { text: "Vận trình công danh của tôi có phụ thuộc vào hướng nhà không?", logic: 'CAREER_FENGSHUI_HOME' },
        { text: "Tôi có số làm trong ngành du lịch, lữ hành không?", logic: 'CAREER_SECTOR_TRAVEL' },
        { text: "Làm sao để phát hiện sớm những rủi ro trong công nghiệp?", logic: 'CAREER_SIGNS_RISK' },
        { text: "Tôi nên làm gì khi cấp dưới có ý định thay thế mình?", logic: 'CAREER_HURDLE_SUBORDINATE' },
        { text: "Tôi có duyên với các công việc liên quan đến thể thao không?", logic: 'CAREER_SECTOR_SPORT' },
        { text: "Vận trình sự nghiệp của tôi vượng vào mùa nào trong năm?", logic: 'CAREER_TIMING_SEASON' },
        { text: "Tôi có nên đầu tư vào việc học ngoại ngữ để thăng tiến?", logic: 'CAREER_ACTION_LANGUAGE' },
        { text: "Lá số có 'Văn Xương' trợ giúp việc học hành thi cử không?", logic: 'CAREER_STARS_VAN_XUONG' },
        { text: "Tôi có năng khiếu quản trị nhân sự không?", logic: 'CAREER_BOSS_HR' },
        { text: "Tôi nên đeo trang sức gì để thu hút tài lộc công danh?", logic: 'CAREER_FENGSHUI_JEWELRY' },
        { text: "Tôi có duyên với ngành nông nghiệp công nghệ cao không?", logic: 'CAREER_SECTOR_AGRI' },
        { text: "Làm sao để duy trì phong độ đỉnh cao trong thời gian dài?", logic: 'CAREER_ACTION_STAMINA' },
        { text: "Tôi có nên nhận lời mời cộng tác từ đối thủ cạnh tranh?", logic: 'CAREER_ACTION_RIVAL' },
        { text: "Vận trình công danh của tôi có bị cản bởi 'Tuế Sát' không?", logic: 'CAREER_HURDLE_TUE_SAT' },
        { text: "Tôi có số trở thành người nổi tiếng, có sức ảnh hưởng?", logic: 'CAREER_TYPE_INFLUENCER' },
        { text: "Làm sao để hóa giải vận đen khi vừa thay đổi chỗ làm?", logic: 'CAREER_ACTION_LUCK_FIX' },
        { text: "Tôi nên làm gì để nhận được sự tin tưởng tuyệt đối từ khách hàng?", logic: 'CAREER_ACTION_TRUST' },
        { text: "Tôi có duyên với ngành tâm lý học, tâm linh không?", logic: 'CAREER_SECTOR_SPIRITUAL' },
        { text: "Lá số có 'Lộc Tồn' mang lại tiền bạc vững vàng từ chức vụ?", logic: 'CAREER_STARS_LOC_TON' },
        { text: "Tôi có năng lực lãnh đạo trong những tình huống cấp bách?", logic: 'CAREER_BOSS_EMERGENCY' },
        { text: "Tôi nên chọn văn phòng quay về hướng nào để đại cát?", logic: 'CAREER_FENGSHUI_DIRECTION' },
        { text: "Tôi có thực sự phù hợp với ngành xây dựng không?", logic: 'CAREER_SECTOR_CONSTRUCTION' },
        { text: "Làm sao để biết một công ty có văn hóa hợp mệnh với mình?", logic: 'CAREER_SIGNS_CULTURE' },
        { text: "Hậu vận của tôi có được ghi danh vào lịch sử nghề nghiệp không?", logic: 'CAREER_LEGACY_FAME' }
    ],
    love: [
        { text: "Tình duyên của tôi là nợ hay là phúc?", logic: 'LOVE_NATURE_DEBT_OR_BLESS' },
        { text: "Tôi nên kết hôn sớm hay muộn thì hạnh phúc?", logic: 'LOVE_TIMING_MARRIAGE' },
        { text: "Người bạn đời của tôi có tính cách như thế nào?", logic: 'LOVE_SPOUSE_PERSONALITY' },
        { text: "Cung Phu Thê của tôi gặp xung hay hợp?", logic: 'LOVE_SPOUSE_PALACE_STATUS' },
        { text: "Khi nào tôi sẽ gặp được 'ý trung nhân' của đời mình?", logic: 'LOVE_TIMING_MEET' },
        { text: "Tại sao đường tình duyên của tôi thường lận đận?", logic: 'LOVE_HURDLE_LONELY' },
        { text: "Tôi và người yêu hiện tại có duyên nợ sâu nặng không?", logic: 'LOVE_DUYEN_NO_CURRENT' },
        { text: "Vợ/chồng tôi có phải là người có tài lộc vượng không?", logic: 'LOVE_SPOUSE_WEALTH' },
        { text: "Tôi có số hưởng phúc nhờ người bạn đời không?", logic: 'LOVE_SPOUSE_SUPPORT' },
        { text: "Làm sao để hóa giải mâu thuẫn trong quan hệ vợ chồng?", logic: 'LOVE_HURDLE_CONFLICT' },
        { text: "Mối quan hệ của tôi có bị can thiệp bởi người thứ ba không?", logic: 'LOVE_HURDLE_THIRD_PERSON' },
        { text: "Duyên phận của tôi với người cũ đã thực sự kết thúc chưa?", logic: 'LOVE_DUYEN_EX' },
        { text: "Tôi nên chọn người có can chi gì thì hợp mệnh?", logic: 'LOVE_PARTNER_COMPATIBILITY' },
        { text: "Tình duyên của tôi sẽ khởi sắc vào năm nào?", logic: 'LOVE_YEARLY_PEAK' },
        { text: "Cung Phu Thê có chứa các sao Quý nhân nào không?", logic: 'LOVE_SPOUSE_NOBLE' },
        { text: "Lá số có dấu hiệu của việc kết hôn nhiều lần không?", logic: 'LOVE_MULTIPLE_MARRIAGE' },
        { text: "Tôi có nên chủ động trong tình cảm hay chờ đợi?", logic: 'LOVE_ACTION_STRATEGY' },
        { text: "Vẻ ngoài của 'nửa kia' qua lá số Bát tự như thế nào?", logic: 'LOVE_SPOUSE_LOOKS' },
        { text: "Sự nghiệp của tôi có bị ảnh hưởng bởi chuyện tình cảm không?", logic: 'LOVE_IMPACT_ON_CAREER' },
        { text: "Tôi có duyên với người ở xa hay người gần nhà?", logic: 'LOVE_PARTNER_ORIGIN' },
        { text: "Lá số có sao 'Đào Hoa' hay 'Hồng Loan' chiếu mệnh không?", logic: 'LOVE_ROMANCE_STARS' },
        { text: "Làm sao để giữ lửa hạnh phúc khi gặp hạn 'Cô Quả'?", logic: 'LOVE_HURDLE_CO_QUA' },
        { text: "Tôi có số kết hôn với người giàu sang không?", logic: 'LOVE_SPOUSE_STATUS' },
        { text: "Đường tình duyên của tôi sau khi sinh con sẽ thế nào?", logic: 'LOVE_AFTER_KIDS' },
        { text: "Tôi có nên tin vào mai mối hay tự mình tìm kiếm?", logic: 'LOVE_MATCH_METHOD' },
        { text: "Những xung khắc nào trong lá số cần hóa giải để có hôn nhân bền vững?", logic: 'LOVE_HURDLE_CLASH' },
        { text: "Tôi có duyên với người ngoại quốc không?", logic: 'LOVE_PARTNER_FOREIGN' },
        { text: "Làm sao để biết mình đã gặp đúng người theo vận mệnh?", logic: 'LOVE_SIGNS_OF_TRUE' },
        { text: "Tình yêu của tôi thường bị ngăn trở bởi yếu tố nào?", logic: 'LOVE_HURDLE_BARRIER' },
        { text: "Tôi có số được người yêu che chở, bao bọc không?", logic: 'LOVE_SPOUSE_PROTECT' },
        { text: "Mối quan hệ của tôi có gặp biến động vào năm 'Thái Tuế' không?", logic: 'LOVE_YEARLY_CHANGE' },
        { text: "Làm sao để tăng vận đào hoa cho người độc thân?", logic: 'LOVE_ACTION_BOOST' },
        { text: "Tôi có duyên với người lớn tuổi hơn hay ít tuổi hơn?", logic: 'LOVE_PARTNER_AGE_GAP' },
        { text: "Người bạn đời của tôi có phải là người đào hoa không?", logic: 'LOVE_SPOUSE_CHARM' },
        { text: "Tôi có nên thay đổi tính cách để giữ gìn hạnh phúc?", logic: 'LOVE_ACTION_ADAPT' },
        { text: "Vận trình tình cảm của tôi vượng vào mùa nào?", logic: 'LOVE_TIMING_SEASON' },
        { text: "Tôi có duyên với các mối quan hệ chớp nhoáng không?", logic: 'LOVE_TYPE_QUICK' },
        { text: "Làm sao để chữa lành vết thương lòng sau đổ vỡ?", logic: 'LOVE_ACTION_HEAL' },
        { text: "Người yêu tôi có phải là người trọng vật chất không?", logic: 'LOVE_PARTNER_MATERIAL' },
        { text: "Tôi có số được cha mẹ hai bên ủng hộ chuyện tình cảm?", logic: 'LOVE_FAMILY_SUPPORT' },
        { text: "Lá số có 'Thiên Hỷ' báo hiệu hỷ sự sắp tới không?", logic: 'LOVE_STARS_THIEN_HY' },
        { text: "Làm sao để biết đối phương có đang lừa dối mình?", logic: 'LOVE_SIGNS_DECEIT' },
        { text: "Tôi có duyên với người trong ngành nghệ thuật không?", logic: 'LOVE_PARTNER_ART' },
        { text: "Tình yêu của tôi có bền vững khi yêu xa không?", logic: 'LOVE_PARTNER_DISTANCE' },
        { text: "Tôi nên đặt gì trong phòng ngủ để tình cảm thêm mặn nồng?", logic: 'LOVE_FENGSHUI_BEDROOM' },
        { text: "Những tháng nào trong năm là 'điểm đen' cho tình cảm?", logic: 'LOVE_TIMING_BAD_MONTH' },
        { text: "Tôi có nên quay lại với người yêu cũ không?", logic: 'LOVE_ACTION_EX_BACK' },
        { text: "Mối quan hệ hiện tại có dẫn đến hôn nhân không?", logic: 'LOVE_CURRENT_DESTINY' },
        { text: "Tôi có số kết hôn với người cùng quê không?", logic: 'LOVE_PARTNER_HOME' },
        { text: "Làm sao để thu hút người bạn đời lý tưởng?", logic: 'LOVE_ACTION_ATTRACT' },
        { text: "Lá số có 'Cô Thần' gây ra sự cô đơn trong tâm hồn không?", logic: 'LOVE_STARS_CO_THAN' },
        { text: "Tôi có nên công khai chuyện tình cảm lên mạng xã hội?", logic: 'LOVE_ACTION_SOCIAL' },
        { text: "Người bạn đời của tôi có phải là người nóng tính không?", logic: 'LOVE_SPOUSE_TEMPER' },
        { text: "Tôi có số được người yêu tặng quà cáp giá trị không?", logic: 'LOVE_LUCK_GIFT' },
        { text: "Làm sao để biết mình và người ấy có 'tướng phu thê'?", logic: 'LOVE_SIGNS_SOULMATE' },
        { text: "Tôi có duyên với người làm trong ngành quân đội, công an?", logic: 'LOVE_PARTNER_OFFICER' },
        { text: "Vận trình tình cảm của tôi sau tuổi 35 sẽ như thế nào?", logic: 'LOVE_AGE_35_PLUS' },
        { text: "Tôi có nên tin vào lời bói toán về chuyện tình duyên?", logic: 'LOVE_ACTION_BELIEF' },
        { text: "Lá số có 'Hàm Trì' chủ về sự lãng mạn nhưng dễ thị phi?", logic: 'LOVE_STARS_HAM_TRI' },
        { text: "Tôi có số kết hôn với người có địa vị xã hội cao?", logic: 'LOVE_SPOUSE_POWER' },
        { text: "Làm sao để hóa giải hạn 'Quả Tú' đang đeo bám?", logic: 'LOVE_STARS_QUA_TU' },
        { text: "Tôi có nên chủ động cầu hôn đối phương không?", logic: 'LOVE_ACTION_PROPOSE' },
        { text: "Người yêu tôi có phải là người hiếu thảo với cha mẹ?", logic: 'LOVE_PARTNER_PIETY' },
        { text: "Tôi có số gặp tình yêu sét đánh không?", logic: 'LOVE_TYPE_FLASH' },
        { text: "Làm sao để duy trì sự lãng mạn sau nhiều năm chung sống?", logic: 'LOVE_ACTION_ROMANCE' },
        { text: "Tôi có duyên với người có ngoại hình xuất sắc không?", logic: 'LOVE_SPOUSE_BEAUTY' },
        { text: "Tình yêu của tôi có bị ngăn cản bởi tôn giáo, sắc tộc?", logic: 'LOVE_HURDLE_CULTURE' },
        { text: "Tôi nên đi du lịch hướng nào để tìm thấy tình yêu?", logic: 'LOVE_LOCATION_TRAVEL' },
        { text: "Lá số có 'Mộc Dục' chủ về sự đào hoa đa tình không?", logic: 'LOVE_STARS_MOC_DUC' },
        { text: "Tôi có năng lực thấu cảm tâm tư của đối phương không?", logic: 'LOVE_PSYCHOLOGY' },
        { text: "Làm sao để vượt qua sự phản bội trong tình cảm?", logic: 'LOVE_ACTION_BETRAY' },
        { text: "Tôi có nên thử hẹn hò qua các ứng dụng trực tuyến?", logic: 'LOVE_ACTION_APP' },
        { text: "Người bạn đời của tôi có năng khiếu thiên bẩm gì?", logic: 'LOVE_SPOUSE_TALENT' },
        { text: "Tôi có số được người yêu cũ giúp đỡ trong sự nghiệp?", logic: 'LOVE_LUCK_EX_HELP' },
        { text: "Làm sao để biết người ấy có phải là 'định mệnh' của mình?", logic: 'LOVE_SIGNS_DESTINY' },
        { text: "Tôi có duyên với người có tính cách trầm mặc, ít nói?", logic: 'LOVE_PARTNER_SILENT' },
        { text: "Vận trình tình cảm của tôi có bị ảnh hưởng bởi hướng giường?", logic: 'LOVE_FENGSHUI_BED' },
        { text: "Tôi có số kết hôn với người từng đổ vỡ một lần?", logic: 'LOVE_SPOUSE_DIVORCED' },
        { text: "Làm sao để giữ gìn bí mật riêng tư trong hôn nhân?", logic: 'LOVE_ACTION_PRIVACY' },
        { text: "Tôi có duyên với người làm việc trong ngành giáo dục?", logic: 'LOVE_PARTNER_TEACHER' },
        { text: "Lá số có 'Thiên Đức' giúp gặp dữ hóa lành trong tình cảm?", logic: 'LOVE_STARS_THIEN_DUC' },
        { text: "Tôi có nên nhường nhịn đối phương trong mọi tình huống?", logic: 'LOVE_ACTION_CONCEDE' },
        { text: "Người bạn đời của tôi có phải là người biết giữ tiền?", logic: 'LOVE_SPOUSE_MONEY' },
        { text: "Tôi có số được người yêu bao nuôi, lo lắng tài chính?", logic: 'LOVE_SPOUSE_WEALTH_SUPPORT' },
        { text: "Làm sao để phân biệt giữa tình yêu và sự ngưỡng mộ?", logic: 'LOVE_SIGNS_FEELING' },
        { text: "Tôi có duyên với người có chiều cao nổi bật không?", logic: 'LOVE_SPOUSE_HEIGHT' },
        { text: "Tình yêu của tôi có bị ảnh hưởng bởi 'Vong Thần' không?", logic: 'LOVE_STARS_VONG_THAN' },
        { text: "Tôi có nên tham gia các lớp học về tâm lý hôn nhân?", logic: 'LOVE_ACTION_LEARN' },
        { text: "Người yêu tôi có phải là người thích sự tự do, bay nhảy?", logic: 'LOVE_PARTNER_FREE' },
        { text: "Tôi có số gặp lại mối tình đầu sau nhiều năm xa cách?", logic: 'LOVE_LUCK_FIRST_LOVE' },
        { text: "Làm sao để hóa giải sự ghen tuông vô lối trong tình yêu?", logic: 'LOVE_ACTION_JEALOUSY' },
        { text: "Tôi có duyên với người có giọng nói truyền cảm không?", logic: 'LOVE_SPOUSE_VOICE' },
        { text: "Vận trình tình cảm của tôi sau khi đổi nơi ở sẽ thế nào?", logic: 'LOVE_LOCATION_MOVE' },
        { text: "Tôi có số kết hôn với người có cùng đam mê, sở thích?", logic: 'LOVE_SPOUSE_HOBBY' },
        { text: "Làm sao để duy trì sự tôn trọng lẫn nhau trong tình yêu?", logic: 'LOVE_ACTION_RESPECT' },
        { text: "Tôi có duyên với người làm trong lĩnh vực y tế?", logic: 'LOVE_PARTNER_HEALTH' },
        { text: "Lá số có 'Nguyệt Đức' báo hiệu hôn nhân viên mãn không?", logic: 'LOVE_STARS_NGUYET_DUC' },
        { text: "Tôi có nên thử sống thử trước khi kết hôn?", logic: 'LOVE_ACTION_COHABIT' },
        { text: "Người bạn đời của tôi có phải là người có thực tài?", logic: 'LOVE_SPOUSE_SKILL' },
        { text: "Hậu vận của tôi có được hưởng hạnh phúc tuổi già bên bạn đời?", logic: 'LOVE_LATE_LIFE' }
    ],
    wealth: [
        { text: "Cung tài lộc của tôi vượng hay suy?", logic: 'WEALTH_PALACE_STRENGTH' },
        { text: "Tôi có số phát tài bất ngờ (hoành tài) không?", logic: 'WEALTH_HOANH_TAI' },
        { text: "Làm sao để giữ được tiền bạc không bị thất thoát?", logic: 'WEALTH_HURDLE_LOSS' },
        { text: "Tôi nên đầu tư vào lĩnh vực nào để sinh lời nhất?", logic: 'WEALTH_SECTOR_ELEMENT' },
        { text: "Tài vận của tôi sẽ phát đạt nhất vào giai đoạn nào?", logic: 'WEALTH_LUCK_CYCLE_PEAK' },
        { text: "Tôi có hợp với việc chơi chứng khoán hay tiền ảo không?", logic: 'WEALTH_ACTION_SPECULATION' },
        { text: "Lá số của tôi có 'Kho tàng' (Mộ khố) tài lộc không?", logic: 'WEALTH_SPECIFIC_GEJU_TREASURE' },
        { text: "Tại sao tôi kiếm được tiền nhưng không tích lũy được?", logic: 'WEALTH_HURDLE_LEAK' },
        { text: "Tôi có số hưởng gia sản từ cha mẹ không?", logic: 'WEALTH_ANCESTOR_BLESS' },
        { text: "Việc làm từ thiện có giúp tôi tăng cường vận tài không?", logic: 'WEALTH_ACTION_CHARITY' },
        { text: "Tôi nên đặt bàn thờ thần tài hướng nào để hút lộc?", logic: 'WEALTH_FENGSHUI_DIRECTION' },
        { text: "Sự xuất hiện của 'Tỷ Kiên' có đang cướp tài của tôi không?", logic: 'WEALTH_HURDLE_ROB' },
        { text: "Năm nay tôi có nên mua nhà hay mua xe không?", logic: 'WEALTH_ACTION_PURCHASE' },
        { text: "Tôi có duyên với các khoản lộc từ người lạ không?", logic: 'WEALTH_LUCK_RANDOM' },
        { text: "Làm sao để kích hoạt cung tài lộc đang bị đóng lại?", logic: 'WEALTH_ACTION_ACTIVATE' },
        { text: "Vận may tiền bạc của tôi đến từ hướng nào?", logic: 'WEALTH_LOCATION_SOURCE' },
        { text: "Tôi có nên chung vốn đầu tư với bạn bè không?", logic: 'WEALTH_PARTNER_INVEST' },
        { text: "Tiền bạc của tôi thường mất đi vì lý do gì?", logic: 'WEALTH_HURDLE_WHY_LOSS' },
        { text: "Tôi có số trúng số hay nhận giải thưởng lớn không?", logic: 'WEALTH_LUCK_GAME' },
        { text: "Hậu vận của tôi có giàu sang phú quý không?", logic: 'WEALTH_LATE_LIFE' },
        { text: "Tài bảo trong lá số là 'Chính Tài' hay 'Thiên Tài' chiếm ưu thế?", logic: 'WEALTH_NATURE_CHINH_THIEN' },
        { text: "Làm sao để hóa giải hạn 'Hao Tài' trong năm nay?", logic: 'WEALTH_HURDLE_YEARLY_HAO' },
        { text: "Tôi có nên vay vốn để mở rộng kinh doanh không?", logic: 'WEALTH_ACTION_LOAN' },
        { text: "Tiền bạc có phải là gánh nặng tinh thần đối với tôi không?", logic: 'WEALTH_PSYCHOLOGY' },
        { text: "Tôi có duyên với việc kinh doanh vàng bạc, đá quý không?", logic: 'WEALTH_SECTOR_METAL' },
        { text: "Năng lượng hành nào giúp tôi thu hút tiền tài?", logic: 'WEALTH_ELEMENT_ATTRACT' },
        { text: "Lá số có dấu hiệu của việc trắng tay rồi mới phát đạt không?", logic: 'WEALTH_NATURE_UPS_DOWNS' },
        { text: "Tôi có số được quý nhân ban tặng của cải không?", logic: 'WEALTH_NOBLE_GIFT' },
        { text: "Làm sao để phát triển tài lộc bền vững qua nhiều thế hệ?", logic: 'WEALTH_LEGACY' },
        { text: "Vận tài của tôi có bị ảnh hưởng bởi người phối ngẫu không?", logic: 'WEALTH_SPOUSE_IMPACT' },
        { text: "Tôi có nên tham gia vào các thị trường tài chính quốc tế?", logic: 'WEALTH_ACTION_GLOBAL' },
        { text: "Làm sao để nhận biết các cơ hội làm giàu từ vận trình năm?", logic: 'WEALTH_SIGNS_YEARLY' },
        { text: "Tôi có duyên với công việc thu gom, tái chế không?", logic: 'WEALTH_SECTOR_RECYCLE' },
        { text: "Tài lộc của tôi có vượng hơn sau khi sinh con?", logic: 'WEALTH_AFTER_KIDS' },
        { text: "Làm sao để hóa giải vận rủi khi vừa mất một khoản tiền lớn?", logic: 'WEALTH_ACTION_RECOVER' },
        { text: "Tôi có số trở thành triệu phú nhờ kinh doanh online?", logic: 'WEALTH_TYPE_ONLINE' },
        { text: "Nên đeo đá quý màu gì để chiêu tài lộc?", logic: 'WEALTH_FENGSHUI_STONE' },
        { text: "Tôi có duyên với ngành tư vấn bảo hiểm không?", logic: 'WEALTH_SECTOR_INSURANCE' },
        { text: "Tài vận của tôi có bị cản bởi hướng bếp không?", logic: 'WEALTH_FENGSHUI_KITCHEN' },
        { text: "Tại sao tôi thường gặp may mắn tiền bạc vào mùa xuân?", logic: 'WEALTH_SEASON_SPRING' },
        { text: "Tôi có số được hưởng lộc từ các công việc béo bở không?", logic: 'WEALTH_LUCK_EASY' },
        { text: "Làm sao để bảo vệ tài sản trước những biến động kinh tế?", logic: 'WEALTH_ACTION_SAFEGUARD' },
        { text: "Tôi có duyên với việc săn lùng đồ cổ, vật phẩm có giá trị?", logic: 'WEALTH_SECTOR_ANTIQUE' },
        { text: "Năng lượng từ con số nào trong số điện thoại giúp tôi hút tiền?", logic: 'WEALTH_FENGSHUI_PHONE' },
        { text: "Tôi có số phát đạt nhờ việc đi làm ăn xa xứ?", logic: 'WEALTH_LOCATION_OVERSEAS' },
        { text: "Làm sao để tăng cường sự nhạy bén trong kinh doanh?", logic: 'WEALTH_ACTION_ACUMEN' },
        { text: "Tôi có duyên với các công việc liên quan đến thực phẩm không?", logic: 'WEALTH_SECTOR_FOOD' },
        { text: "Vận tài của tôi có bị ảnh hưởng bởi vận hạn của bạn bè?", logic: 'WEALTH_FRIEND_IMPACT' },
        { text: "Làm sao để biết một dự án đầu tư là an toàn?", logic: 'WEALTH_SIGNS_SAFE' },
        { text: "Tôi có số trở thành đại lý phân phối cho các nhãn hàng lớn?", logic: 'WEALTH_TYPE_AGENCY' },
        { text: "Nên trồng cây gì trong nhà để kích hoạt cung tài lộc?", logic: 'WEALTH_FENGSHUI_PLANT' },
        { text: "Tôi có duyên với ngành công nghiệp giải trí, sòng bài?", logic: 'WEALTH_SECTOR_CASINO' },
        { text: "Tài lộc của tôi có vượng lên nhờ việc thay đổi kiểu tóc?", logic: 'WEALTH_ACTION_STYLE' },
        { text: "Tại sao tôi thường cảm thấy áp lực khi phải quản lý số tiền lớn?", logic: 'WEALTH_MENTAL_HEAVY' },
        { text: "Tôi có số được quý nhân chỉ đường dẫn lối làm giàu?", logic: 'WEALTH_NOBLE_GUIDE' },
        { text: "Làm sao để duy trì sự thịnh vượng bền bỉ qua năm tháng?", logic: 'WEALTH_ACTION_STAMINA' },
        { text: "Tôi có duyên với các công việc liên quan đến kiến trúc không?", logic: 'WEALTH_SECTOR_ARCHI' },
        { text: "Vận tài của tôi có bị cản bởi 'Tuế Phá' không?", logic: 'WEALTH_HURDLE_TUE_PHA' },
        { text: "Tôi có số trúng thưởng từ các chương trình tri ân khách hàng?", logic: 'WEALTH_LUCK_EVENT' },
        { text: "Làm sao để hóa giải tình trạng nợ nần kéo dài?", logic: 'WEALTH_ACTION_DEBT' },
        { text: "Tôi có duyên với ngành xuất nhập khẩu hàng hóa?", logic: 'WEALTH_SECTOR_EXIM' },
        { text: "Tiền bạc có phải là thước đo thành công duy nhất của tôi?", logic: 'WEALTH_PHILOSOPHY' },
        { text: "Tôi có số phát đạt nhờ việc sở hữu nhiều bất động sản?", logic: 'WEALTH_TYPE_LANDLORD' },
        { text: "Nên sử dụng ví màu gì để giữ tiền tốt nhất?", logic: 'WEALTH_FENGSHUI_WALLET' },
        { text: "Tôi có duyên với việc làm trong các quỹ đầu tư mạo hiểm?", logic: 'WEALTH_SECTOR_VC' },
        { text: "Tài lộc của tôi có vượng hơn khi làm việc vào ban đêm?", logic: 'WEALTH_TIME_NIGHT' },
        { text: "Làm sao để biết một người là đối tác mang lại lộc lá?", logic: 'WEALTH_SIGNS_PARTNER' },
        { text: "Tôi có số được thừa kế những bí kíp làm giàu từ tổ tiên?", logic: 'WEALTH_LEGACY_SKILL' },
        { text: "Nên đặt gương ở đâu để nhân đôi tài lộc trong nhà?", logic: 'WEALTH_FENGSHUI_MIRROR' },
        { text: "Tôi có duyên với ngành công nghệ sinh học không?", logic: 'WEALTH_SECTOR_BIOTECH' },
        { text: "Tài vận của tôi có bị ảnh hưởng bởi việc thay đổi tên công ty?", logic: 'WEALTH_ACTION_REBRAND' },
        { text: "Tại sao tôi thường gặp may mắn tiền bạc ở nơi đông người?", logic: 'WEALTH_LOCATION_CROWD' },
        { text: "Tôi có số phát đạt nhờ việc sản xuất hàng thủ công mỹ nghệ?", logic: 'WEALTH_TYPE_CRAFT' },
        { text: "Làm sao để thu hút những nguồn khách hàng cao cấp?", logic: 'WEALTH_ACTION_VIP' },
        { text: "Tôi có duyên với các công việc liên quan đến nước sạch?", logic: 'WEALTH_SECTOR_WATER' },
        { text: "Vận tài của tôi có vượng hơn nếu tôi làm việc độc lập?", logic: 'WEALTH_TYPE_SOLO' },
        { text: "Làm sao để vượt qua nỗi sợ mất tiền khi đầu tư?", logic: 'WEALTH_PSYCH_FEAR' },
        { text: "Tôi có số trở thành chuyên gia phân tích thị trường?", logic: 'WEALTH_TYPE_ANALYST' },
        { text: "Nên sử dụng vật phẩm phong thủy gì để hóa giải sát khí cung tài?", logic: 'WEALTH_FENGSHUI_REMEDY' },
        { text: "Tôi có duyên với ngành công nghiệp phim ảnh, phim trường?", logic: 'WEALTH_SECTOR_FILM' },
        { text: "Tài lộc của tôi có vượng lên nhờ việc tham gia từ thiện?", logic: 'WEALTH_ACTION_GIVE' },
        { text: "Tại sao tôi thường kiếm được tiền từ những ý tưởng kỳ quặc?", logic: 'WEALTH_TYPE_ODD_IDEA' },
        { text: "Tôi có số phát đạt nhờ việc khai thác tài nguyên thiên nhiên?", logic: 'WEALTH_SECTOR_MINING' },
        { text: "Làm sao để nhận biết các dấu hiệu sắp có lộc lá lớn?", logic: 'WEALTH_SIGNS_BIG_LUCK' },
        { text: "Tôi có duyên với các công việc liên quan đến thời trang?", logic: 'WEALTH_SECTOR_FASHION' },
        { text: "Vận tài của tôi có bị cản bởi vị trí đặt két sắt?", logic: 'WEALTH_FENGSHUI_SAFE' },
        { text: "Tôi có số trúng thưởng từ các cuộc thi kiến thức?", logic: 'WEALTH_LUCK_QUIZ' },
        { text: "Làm sao để duy trì tâm thái bình thản dù giàu hay nghèo?", logic: 'WEALTH_MENTAL_ZEN' },
        { text: "Tôi có duyên với ngành đào tạo kỹ năng làm giàu không?", logic: 'WEALTH_SECTOR_EDUCATION' },
        { text: "Tài lộc của tôi có vượng hơn khi đi về phương Đông?", logic: 'WEALTH_LOCATION_EAST' },
        { text: "Tại sao tôi thường gặp khó khăn tiền bạc khi ở gần người thân?", logic: 'WEALTH_FAMILY_HURDLE' },
        { text: "Tôi có số phát đạt nhờ việc môi giới trung gian?", logic: 'WEALTH_TYPE_BROKER' },
        { text: "Làm sao để tối ưu hóa dòng tiền cá nhân theo Bát tự?", logic: 'WEALTH_ACTION_CASHFLOW' },
        { text: "Tôi có duyên với các công việc liên quan đến đồ điện tử?", logic: 'WEALTH_SECTOR_ELEC' },
        { text: "Vận tài của tôi có vượng hơn sau mỗi lần gặp nạn?", logic: 'WEALTH_NATURE_RESET' },
        { text: "Làm sao để thu hút những cơ hội làm ăn bất ngờ?", logic: 'WEALTH_ACTION_LUCK_MAGNET' },
        { text: "Tôi có số trở thành nhà sưu tầm vật phẩm quý hiếm?", logic: 'WEALTH_TYPE_COLLECTOR' },
        { text: "Nên sử dụng tinh dầu thơm gì để chiêu tài lộc vào nhà?", logic: 'WEALTH_FENGSHUI_SCENT' },
        { text: "Tôi có duyên với ngành tổ chức sự kiện, lễ hội?", logic: 'WEALTH_SECTOR_EVENT' },
        { text: "Tài lộc của tôi có được bảo toàn đến cuối đời không?", logic: 'WEALTH_END_LIFE' }
    ],
    health: [
        { text: "Sức khỏe bẩm sinh của tôi cần lưu ý điều gì?", logic: 'HEALTH_NATURE_BORN' },
        { text: "Ngũ hành nào trong lá số của tôi đang bị thiếu hụt?", logic: 'HEALTH_ELEMENT_LACK' },
        { text: "Tôi cần đề phòng các bệnh về bộ phận nào nhất?", logic: 'HEALTH_BODY_SYSTEM' },
        { text: "Chế độ ăn uống nào hợp với mệnh ngũ hành của tôi?", logic: 'HEALTH_ACTION_DIET' },
        { text: "Tôi có gặp hạn nặng về sức khỏe trong năm nay không?", logic: 'HEALTH_YEARLY_RISK' },
        { text: "Làm sao để tăng cường sinh lực qua phương pháp phong thủy?", logic: 'HEALTH_FENGSHUI_BOOST' },
        { text: "Tôi có hợp với việc luyện tập các môn võ thuật không?", logic: 'HEALTH_ACTION_SPORT' },
        { text: "Môi trường sống như thế nào thì tốt cho thần khí của tôi?", logic: 'HEALTH_LOCATION_ENV' },
        { text: "Tôi có nên thực hiện các ca phẫu thuật thẩm mỹ không?", logic: 'HEALTH_ACTION_SURGERY' },
        { text: "Giấc ngủ của tôi bị ảnh hưởng bởi yếu tố can chi nào?", logic: 'HEALTH_HURDLE_SLEEP' },
        { text: "Lá số của tôi có dấu hiệu của việc sống thọ không?", logic: 'HEALTH_LONGEVITY' },
        { text: "Tôi nên chú trọng vào việc tu dưỡng tâm tính ra sao?", logic: 'HEALTH_PSYCHOLOGY' },
        { text: "Hệ tiêu hóa của tôi có thực sự ổn định không?", logic: 'HEALTH_BODY_DIGEST' },
        { text: "Tại sao tôi thường xuyên cảm thấy mệt mỏi vào mùa đông?", logic: 'HEALTH_SEASON_IMPACT' },
        { text: "Màu sắc trang phục nào giúp tôi cải thiện sức khỏe?", logic: 'HEALTH_FENGSHUI_COLOR' },
        { text: "Tôi có duyên với các bài thuốc nam hay thuốc bắc?", logic: 'HEALTH_ACTION_MEDICINE' },
        { text: "Những năm nào tôi cần đặc biệt cẩn trọng về tai nạn?", logic: 'HEALTH_TIMING_ACCIDENT' },
        { text: "Làm sao để giảm bớt áp lực tinh thần qua lá số?", logic: 'HEALTH_HURDLE_STRESS' },
        { text: "Tôi có nên đi định cư ở nơi có khí hậu nóng hay lạnh?", logic: 'HEALTH_LOCATION_CLIMATE' },
        { text: "Sức khỏe của người thân có ảnh hưởng đến tôi không?", logic: 'HEALTH_FAMILY_IMPACT' },
        { text: "Lá số có 'Kình Dương' hay 'Đà La' gây hại cho thể chất không?", logic: 'HEALTH_STARS_HARMFUL' },
        { text: "Làm sao để cân bằng lại ngũ hành đang bị lệch?", logic: 'HEALTH_ACTION_BALANCE' },
        { text: "Tôi có nên tham gia các khóa tu thiền để cải thiện sức khỏe?", logic: 'HEALTH_ACTION_MEDITATION' },
        { text: "Bộ phận nào trên cơ thể là 'yếu điểm' của tôi?", logic: 'HEALTH_BODY_WEAK_POINT' },
        { text: "Tôi có hạn về sông nước hay té ngã trong thời gian tới không?", logic: 'HEALTH_HURDLE_WATER_FALL' },
        { text: "Sức khỏe tâm thần của tôi có thực sự được quan tâm đúng mực?", logic: 'HEALTH_MENTAL' },
        { text: "Làm sao để hóa giải 'Bệnh Phù' trong vận trình cửu cung?", logic: 'HEALTH_ACTION_BENH_PHU' },
        { text: "Tôi có nên thay đổi thói quen sinh hoạt theo can chi giờ không?", logic: 'HEALTH_ACTION_HABIT' },
        { text: "Năng lượng từ cây xanh có giúp tôi hồi phục sức khỏe nhanh không?", logic: 'HEALTH_ELEMENT_WOOD_BOOST' },
        { text: "Tôi có số chịu ảnh hưởng mạnh bởi từ trường của trái đất không?", logic: 'HEALTH_GEOPHYSICAL' },
        { text: "Mùa hè nóng bức có làm suy yếu hành Thủy trong lá số của tôi?", logic: 'HEALTH_SEASON_SUMMER' },
        { text: "Tôi nên tập yoga hay gym để cân bằng năng lượng?", logic: 'HEALTH_ACTION_YOGA_GYM' },
        { text: "Hệ hô hấp của tôi có nhạy cảm với khí bụi không?", logic: 'HEALTH_BODY_RESPIRATORY' },
        { text: "Làm sao để biết một nơi ở có luồng khí độc hại?", logic: 'HEALTH_SIGNS_ENV' },
        { text: "Tôi có duyên với việc điều trị bằng năng lượng sinh học?", logic: 'HEALTH_TYPE_BIO' },
        { text: "Nên sử dụng loại tinh dầu gì để giải tỏa căng thẳng?", logic: 'HEALTH_FENGSHUI_OIL' },
        { text: "Sức khỏe của tôi có vượng lên nhờ việc nuôi thú cưng?", logic: 'HEALTH_ACTION_PET' },
        { text: "Tại sao tôi thường gặp vấn đề về da vào mùa thu?", logic: 'HEALTH_SEASON_AUTUMN' },
        { text: "Tôi có số gặp được thầy giỏi, thuốc hay khi lâm bệnh?", logic: 'HEALTH_LUCK_DOCTOR' },
        { text: "Làm sao để duy trì sự dẻo dai của xương khớp?", logic: 'HEALTH_BODY_BONE' },
        { text: "Mùi hương gỗ có giúp tôi an thần, ngủ ngon hơn không?", logic: 'HEALTH_FENGSHUI_WOOD_SMELL' },
        { text: "Tôi có duyên với các môn thể thao dưới nước không?", logic: 'HEALTH_ACTION_WATER_SPORT' },
        { text: "Vận trình sức khỏe của tôi có bị ảnh hưởng bởi hướng đầu nằm?", logic: 'HEALTH_FENGSHUI_HEAD' },
        { text: "Tôi có số chịu đựng được áp lực công việc cao?", logic: 'HEALTH_MENTAL_STRENGTH' },
        { text: "Làm sao để hóa giải sát khí từ các thiết bị điện tử?", logic: 'HEALTH_FENGSHUI_ELEC_REMEDY' },
        { text: "Tôi có duyên với ngành y học cổ truyền dân tộc không?", logic: 'HEALTH_SECTOR_TRADITIONAL' },
        { text: "Vận trình sức khỏe của tôi vượng lên sau khi ăn chay?", logic: 'HEALTH_ACTION_VEGAN' },
        { text: "Tại sao tôi thường xuyên bị đau đầu khi trời trở gió?", logic: 'HEALTH_ENV_WEATHER' },
        { text: "Tôi có số gặp đại nạn nhưng được quý nhân cứu chữa?", logic: 'HEALTH_LUCK_SAVED' },
        { text: "Làm sao để bảo vệ thị lực trong môi trường thiếu sáng?", logic: 'HEALTH_BODY_EYE' },
        { text: "Tôi nên dùng vật liệu gì cho giường ngủ để hợp mệnh?", logic: 'HEALTH_FENGSHUI_BED_MATERIAL' },
        { text: "Tôi có duyên với các bài tập khí công dưỡng sinh không?", logic: 'HEALTH_ACTION_QIGONG' },
        { text: "Sức khỏe của tôi có bị ảnh hưởng bởi vận hạn của con cái?", logic: 'HEALTH_CHILD_IMPACT' },
        { text: "Tại sao tôi cảm thấy hưng phấn hơn khi ở gần biển?", logic: 'HEALTH_LOCATION_SEA' },
        { text: "Tôi có số phát hiện bệnh sớm nhờ sự nhạy bén của cơ thể?", logic: 'HEALTH_SIGNS_SENSITIVE' },
        { text: "Làm sao để tăng cường hệ miễn dịch tự nhiên?", logic: 'HEALTH_ACTION_IMMUNE' },
        { text: "Tôi nên nghe loại nhạc gì để cân bằng sóng não?", logic: 'HEALTH_ACTION_MUSIC' },
        { text: "Sức khỏe của tôi có vượng lên nhờ việc làm vườn?", logic: 'HEALTH_ACTION_GARDENING' },
        { text: "Tại sao tôi thường gặp ác mộng vào những ngày rằm?", logic: 'HEALTH_TIMING_LUNAR' },
        { text: "Tôi có số sống thọ và minh mẫn đến tận cuối đời?", logic: 'HEALTH_LONG_LIFE_CLEAR' },
        { text: "Làm sao để hóa giải năng lượng tiêu cực từ hàng xóm?", logic: 'HEALTH_FENGSHUI_NEIGHBOR' },
        { text: "Tôi có duyên với việc nghiên cứu y lý, thuốc quý?", logic: 'HEALTH_SECTOR_RESEARCH' },
        { text: "Vận trình sức khỏe của tôi có bị cản bởi 'Tuế Sát'?", logic: 'HEALTH_HURDLE_TUE_SAT' },
        { text: "Tôi có số gặp được thần y trong những lúc nguy kịch?", logic: 'HEALTH_LUCK_GOD_DOCTOR' },
        { text: "Làm sao để duy trì vóc dáng cân đối theo Bát tự?", logic: 'HEALTH_ACTION_SHAPE' },
        { text: "Tôi nên uống loại trà gì để thanh lọc cơ thể?", logic: 'HEALTH_ACTION_TEA' },
        { text: "Sức khỏe của tôi có vượng lên nhờ việc thay đổi nghề nghiệp?", logic: 'HEALTH_CAREER_IMPACT' },
        { text: "Tại sao tôi thường bị dị ứng với các loài hoa lạ?", logic: 'HEALTH_ENV_FLOWER' },
        { text: "Tôi có số vượt qua được những căn bệnh hiểm nghèo?", logic: 'HEALTH_LUCK_OVERCOME' },
        { text: "Làm sao để bảo vệ đôi tai trong môi trường tiếng ồn?", logic: 'HEALTH_BODY_EAR' },
        { text: "Tôi nên sử dụng loại đá gì để cân bằng luân xa?", logic: 'HEALTH_FENGSHUI_CHAKRA' },
        { text: "Tôi có duyên với các phương pháp bấm huyệt, massage?", logic: 'HEALTH_ACTION_MASSAGE' },
        { text: "Vận trình sức khỏe của tôi có vượng hơn khi ở tầng cao?", logic: 'HEALTH_LOCATION_HIGH' },
        { text: "Tại sao tôi thường bị mất ngủ khi có dự án mới?", logic: 'HEALTH_MENTAL_PROJECT' },
        { text: "Tôi có số có sức khỏe phi thường so với người cùng lứa?", logic: 'HEALTH_NATURE_ELITE' },
        { text: "Làm sao để hóa giải 'Bệnh Phù' đang trú ngụ trong nhà?", logic: 'HEALTH_FENGSHUI_BENH_PHU' },
        { text: "Tôi nên đi bộ bao nhiêu bước mỗi ngày để kích vận?", logic: 'HEALTH_ACTION_WALK' },
        { text: "Sức khỏe của tôi có vượng lên nhờ việc học đàn?", logic: 'HEALTH_ACTION_PIANO' },
        { text: "Tại sao tôi thường gặp vấn đề về tim mạch khi nóng giận?", logic: 'HEALTH_BODY_HEART' },
        { text: "Tôi có số được con cháu chăm sóc chu đáo khi về già?", logic: 'HEALTH_LATE_LIFE_CARE' },
        { text: "Làm sao để nhận biết các dấu hiệu suy giảm sinh lực sớm?", logic: 'HEALTH_SIGNS_WEAK' },
        { text: "Tôi nên chọn hướng chạy bộ nào để hấp thụ linh khí?", logic: 'HEALTH_ACTION_RUN_DIR' },
        { text: "Sức khỏe của tôi có vượng lên nhờ việc thay đổi màu sơn nhà?", logic: 'HEALTH_FENGSHUI_WALL' },
        { text: "Tại sao tôi thường bị đau lưng khi làm việc quá sức?", logic: 'HEALTH_BODY_BACK' },
        { text: "Tôi có số hưởng thọ nhưng cần đề phòng tai nạn bất ngờ?", logic: 'HEALTH_NATURE_RISK' },
        { text: "Làm sao để duy trì tinh thần lạc quan trước bệnh tật?", logic: 'HEALTH_MENTAL_OPTIMISM' },
        { text: "Tôi nên sử dụng loại gối gì để bảo vệ đốt sống cổ?", logic: 'HEALTH_FENGSHUI_PILLOW' },
        { text: "Sức khỏe của tôi có vượng lên nhờ việc tham gia ca hát?", logic: 'HEALTH_ACTION_SINGING' },
        { text: "Tại sao tôi thường bị nhiệt miệng vào mùa khô?", logic: 'HEALTH_ENV_DRY' },
        { text: "Tôi có số được quý nhân bảo hộ về mặt thể chất?", logic: 'HEALTH_LUCK_GUARD' },
        { text: "Làm sao để hóa giải năng lượng xấu từ bệnh viện?", logic: 'HEALTH_ACTION_HOSPITAL_CLEAN' },
        { text: "Tôi có duyên với các bài tập hít thở sâu, Yoga Nidra?", logic: 'HEALTH_ACTION_BREATH' },
        { text: "Vận trình sức khỏe của tôi có vượng hơn khi đi về hướng Bắc?", logic: 'HEALTH_LOCATION_NORTH' },
        { text: "Tại sao tôi thường bị khớp khi tiếp xúc với nước đá?", logic: 'HEALTH_BODY_JOINT' },
        { text: "Tôi có số phục hồi sức khỏe thần tốc sau chấn thương?", logic: 'HEALTH_LUCK_RECOVERY' },
        { text: "Làm sao để duy trì sự trẻ trung lâu dài qua Bát tự?", logic: 'HEALTH_ACTION_YOUTH' },
        { text: "Tôi nên chọn loại nệm gì để có giấc ngủ sâu?", logic: 'HEALTH_FENGSHUI_MATTRESS' },
        { text: "Sức khỏe của tôi có vượng lên nhờ việc tập viết thư pháp?", logic: 'HEALTH_ACTION_CALLIGRAPHY' },
        { text: "Tại sao tôi thường gặp vấn đề về gan khi thức khuya?", logic: 'HEALTH_BODY_LIVER' },
        { text: "Hậu vận của tôi có thực sự bình an vô sự về mặt thể chất?", logic: 'HEALTH_END_LIFE_PEACE' }
    ],
    children: [
        { text: "Duyên phận của tôi với con cái như thế nào?", logic: 'KIDS_NATURE_DUYEN' },
        { text: "Con cái của tôi sau này có hiếu thảo và thành đạt không?", logic: 'KIDS_FUTURE_SUCCESS' },
        { text: "Tôi nên sinh con vào năm nào thì hợp tuổi bố mẹ?", logic: 'KIDS_TIMING_BIRTH' },
        { text: "Cung Tử Tức của tôi có gặp các sao hung sát không?", logic: 'KIDS_PALACE_STARS' },
        { text: "Số lượng con cái qua lá số Bát tự là bao nhiêu?", logic: 'KIDS_QUANTITY' },
        { text: "Làm sao để giáo dục con cái thuận theo mệnh cách?", logic: 'KIDS_ACTION_EDU' },
        { text: "Con cái có mang lại tài lộc cho gia đình tôi không?", logic: 'KIDS_IMPACT_WEALTH' },
        { text: "Mối quan hệ giữa tôi và con cái có gặp xa cách không?", logic: 'KIDS_RELATION_DISTANCE' },
        { text: "Tôi có duyên nuôi con nuôi hay giúp đỡ trẻ em không?", logic: 'KIDS_DUYEN_ADOPT' },
        { text: "Giới tính của các con qua lá số có thể dự đoán không?", logic: 'KIDS_GENDER_DYNAMICS' },
        { text: "Tôi nên đặt tên con theo hành gì để bổ trợ mệnh?", logic: 'KIDS_ACTION_NAMING' },
        { text: "Con cái của tôi có năng khiếu về lĩnh vực gì?", logic: 'KIDS_FUTURE_TALENT' },
        { text: "Năm nào là thời điểm tốt để cầu con?", logic: 'KIDS_TIMING_CONCEIVE' },
        { text: "Sức khỏe của con cái tôi cần lưu ý giai đoạn nào?", logic: 'KIDS_FUTURE_HEALTH' },
        { text: "Con cái có là động lực để tôi phát triển sự nghiệp không?", logic: 'KIDS_IMPACT_CAREER' },
        { text: "Tôi có gặp khó khăn trong việc sinh nở không?", logic: 'KIDS_HURDLE_BIRTH' },
        { text: "Làm sao để tăng phúc đức cho cung Tử Tức?", logic: 'KIDS_ACTION_BLECC' },
        { text: "Con cái có hợp với việc đi du học sớm không?", logic: 'KIDS_FUTURE_STUDY_ABROAD' },
        { text: "Tính cách của đứa con đầu lòng sẽ như thế nào?", logic: 'KIDS_FIRST_BORN_PERSON' },
        { text: "Hậu vận tôi có được nhờ cậy con cái không?", logic: 'KIDS_LATE_LIFE_SUPPORT' },
        { text: "Lá số có sao 'Thiên Hỷ' báo hiệu tin vui về con cái không?", logic: 'KIDS_STARS_THIEN_HY' },
        { text: "Làm sao để hóa giải xung khắc giữa các con?", logic: 'KIDS_HURDLE_SIBLING_CLASH' },
        { text: "Con cái có thừa hưởng được quý nhân của bố mẹ không?", logic: 'KIDS_LEGACY_NOBLE' },
        { text: "Tôi nên chuẩn bị gì cho tương lai của con cái theo Bát tự?", logic: 'KIDS_ACTION_PREPARE' },
        { text: "Mối liên hệ giữa trụ giờ và cung con cái có gì đặc biệt?", logic: 'KIDS_SPECIFIC_PILLAR_HOUR' },
        { text: "Tôi có nên ép buộc con cái theo nghiệp của gia đình?", logic: 'KIDS_ACTION_GUIDE' },
        { text: "Con cái có giúp tôi giải tỏa những khúc mắc trong cuộc sống?", logic: 'KIDS_PSYCHOLOGY' },
        { text: "Lá số có dấu hiệu của việc con cái phải sống xa nhà không?", logic: 'KIDS_RELATION_FAR' },
        { text: "Làm sao để nhận biết được tiềm năng của con từ lúc nhỏ?", logic: 'KIDS_SIGNS_TALENT' },
        { text: "Phúc đức của tôi có truyền lại được trọn vẹn cho con không?", logic: 'KIDS_LEGACY_LUCK' },
        { text: "Nên trang trí phòng trẻ em như thế nào để kích hoạt trí tuệ?", logic: 'KIDS_FENGSHUI_ROOM' },
        { text: "Tôi có duyên với việc sinh đôi hay sinh ba không?", logic: 'KIDS_TYPE_MULTIPLE' },
        { text: "Con cái có vượng vận hơn nếu tôi sinh con ở nước ngoài?", logic: 'KIDS_LOCATION_BIRTH' },
        { text: "Làm sao để con cái luôn nghe lời mà không cần dùng roi vọt?", logic: 'KIDS_ACTION_COMM' },
        { text: "Tôi có số được con cái báo hiếu bằng vật chất?", logic: 'KIDS_LUCK_MONEY' },
        { text: "Tính cách của đứa con thứ hai sẽ khác gì con đầu?", logic: 'KIDS_SECOND_BORN_PERSON' },
        { text: "Làm sao để hóa giải hạn 'Kim Xà Thiết Tỏa' cho con?", logic: 'KIDS_HURDLE_KIM_XA' },
        { text: "Tôi có duyên với việc giáo dục trẻ em khuyết tật, tài năng?", logic: 'KIDS_TYPE_SPECIAL' },
        { text: "Con cái có giúp tôi hàn gắn mối quan hệ vợ chồng?", logic: 'KIDS_IMPACT_MARRIAGE' },
        { text: "Nên cho con học môn nghệ thuật gì để bổ khuyết ngũ hành?", logic: 'KIDS_ACTION_ART' },
        { text: "Tôi có số gặp khó khăn về đường con cái lúc trẻ?", logic: 'KIDS_TIMING_CHALLENGE' },
        { text: "Làm sao để con cái phát triển toàn diện cả thể chất lẫn tinh thần?", logic: 'KIDS_ACTION_HOLISTIC' },
        { text: "Tôi có duyên với việc truyền nghề cho con cái không?", logic: 'KIDS_LEGACY_TRADE' },
        { text: "Con cái có vượng vận nếu tôi đổi hướng bàn thờ gia tiên?", logic: 'KIDS_FENGSHUI_ALTAR' },
        { text: "Tại sao con cái tôi thường có tính cách bướng bỉnh?", logic: 'KIDS_HURDLE_STUBBORN' },
        { text: "Tôi có số được con cái rước đi ở cùng khi về già?", logic: 'KIDS_LATE_LIFE_MOVE' },
        { text: "Làm sao để bảo vệ con cái trước những nguồn năng lượng xấu?", logic: 'KIDS_ACTION_PROTECT' },
        { text: "Con cái có năng khiếu về ngoại giao, ngôn ngữ không?", logic: 'KIDS_FUTURE_LANG' },
        { text: "Nên cho con đeo vật phẩm phong thủy gì để bình an?", logic: 'KIDS_FENGSHUI_AMULET' },
        { text: "Tôi có số sinh con hợp tuổi với cả bố và mẹ?", logic: 'KIDS_LUCK_AGE' },
        { text: "Làm sao để khơi dậy lòng nhân ái ở con cái?", logic: 'KIDS_ACTION_MORAL' },
        { text: "Con cái có vượng vận nhờ phúc đức của ông bà không?", logic: 'KIDS_LEGACY_GRAND' },
        { text: "Tại sao tôi và con cái thường xảy ra tranh cãi vô lý?", logic: 'KIDS_HURDLE_CLASH' },
        { text: "Tôi có số được nhờ con rể hay con dâu không?", logic: 'KIDS_LUCK_IN_LAW' },
        { text: "Làm sao để chọn trường học hợp mệnh cho con?", logic: 'KIDS_ACTION_SCHOOL' },
        { text: "Con cái có vượng vận hơn sau mỗi lần tôi thăng tiến?", logic: 'KIDS_CAREER_SYNC' },
        { text: "Nên cho con học môn thể thao gì để rèn luyện ý chí?", logic: 'KIDS_ACTION_SPORT' },
        { text: "Tôi có duyên với việc làm cha mẹ đơn thân không?", logic: 'KIDS_TYPE_SINGLE' },
        { text: "Con cái có là niềm tự hào lớn nhất của tôi khi về già?", logic: 'KIDS_LATE_LIFE_PRIDE' },
        { text: "Làm sao để hóa giải sao 'Thái Tuế' ảnh hưởng đến con?", logic: 'KIDS_HURDLE_TUE_SAT' },
        { text: "Tôi có số sinh con có dung mạo khôi ngô, tuấn tú?", logic: 'KIDS_FUTURE_LOOKS' },
        { text: "Làm sao để biết con cái có đang gặp áp lực học đường?", logic: 'KIDS_SIGNS_STRESS' },
        { text: "Con cái có vượng vận nhờ việc tôi tham gia công tác xã hội?", logic: 'KIDS_ACTION_CHARITY' },
        { text: "Nên cho con sử dụng màu sắc gì cho vật dụng cá nhân?", logic: 'KIDS_FENGSHUI_COLOR' },
        { text: "Tôi có số được con cái lo lắng chuyện hậu sự chu tất?", logic: 'KIDS_LATE_LIFE_END' },
        { text: "Làm sao để xây dựng tình bạn thân thiết với con?", logic: 'KIDS_ACTION_FRIEND' },
        { text: "Con cái có năng khiếu về toán học, tư duy logic không?", logic: 'KIDS_FUTURE_LOGIC' },
        { text: "Tôi có duyên với việc sinh con vào ngày lành tháng tốt?", logic: 'KIDS_LUCK_TIME' },
        { text: "Làm sao để con cái tự lập từ sớm theo Bát tự?", logic: 'KIDS_ACTION_INDEP' },
        { text: "Con cái có vượng vận nhờ việc tôi thay đổi thói quen xấu?", logic: 'KIDS_ACTION_HABIT' },
        { text: "Tại sao con cái tôi thường hay ốm vặt vào mùa chuyển mùa?", logic: 'KIDS_HURDLE_HEALTH' },
        { text: "Tôi có số được con cái dẫn đi du lịch khắp nơi?", logic: 'KIDS_LUCK_TRAVEL' },
        { text: "Làm sao để hóa giải hạn 'Đào Hoa' sát cho con?", logic: 'KIDS_HURDLE_ROMANCE' },
        { text: "Con cái có năng khiếu về công nghệ, máy móc không?", logic: 'KIDS_FUTURE_TECH' },
        { text: "Nên cho con ăn những thực phẩm gì để bổ trợ hành thiếu?", logic: 'KIDS_ACTION_DIET' },
        { text: "Tôi có số sinh con có trí tuệ vượt trội người thường?", logic: 'KIDS_NATURE_GENIUS' },
        { text: "Làm sao để khích lệ con cái khi chúng gặp thất bại?", logic: 'KIDS_ACTION_CHEER' },
        { text: "Con cái có vượng vận nhờ việc tôi bồi đắp kiến thức Bát tự?", logic: 'KIDS_ACTION_LEARN' },
        { text: "Tại sao con cái tôi thường có xu hướng sống hướng nội?", logic: 'KIDS_HURDLE_INTROID' },
        { text: "Tôi có số được con cái kính trọng như một người thầy?", logic: 'KIDS_RELATION_MENTOR' },
        { text: "Làm sao để hóa giải sao 'Kình Dương' trong cung Tử Tức?", logic: 'KIDS_STARS_REMEDY' },
        { text: "Nên chọn hướng ngồi học cho con như thế nào để đỗ đạt?", logic: 'KIDS_FENGSHUI_STUDY' },
        { text: "Con cái có năng khiếu về âm nhạc, nhịp điệu không?", logic: 'KIDS_FUTURE_MUSIC' },
        { text: "Tôi có duyên với việc nuôi dạy con cái thành những nhà lãnh đạo?", logic: 'KIDS_TYPE_LEADER' },
        { text: "Làm sao để duy trì sự gắn kết gia đình qua nhiều thế hệ?", logic: 'KIDS_ACTION_BOND' },
        { text: "Con cái có vượng vận hơn sau khi tôi làm lễ quy y, tu tập?", logic: 'KIDS_ACTION_FAITH' },
        { text: "Tại sao con cái tôi thường có đam mê với các hoạt động cộng đồng?", logic: 'KIDS_FUTURE_SOCIAL' },
        { text: "Tôi có số được con cái thừa kế những đức tính tốt đẹp nhất?", logic: 'KIDS_LEGACY_VIRTUE' },
        { text: "Làm sao để con cái hiểu và trân trọng giá trị đồng tiền?", logic: 'KIDS_ACTION_MONEY' },
        { text: "Con cái có là gương phản chiếu những góc khuất trong tôi?", logic: 'KIDS_PSYCHOLOGY_REFLECTION' },
        { text: "Nên chọn màu xe cho con như thế nào để an toàn?", logic: 'KIDS_FENGSHUI_CAR' },
        { text: "Tôi có duyên với việc sinh con vào năm đại vận tốt?", logic: 'KIDS_LUCK_CYCLE' },
        { text: "Làm sao để hóa giải hạn 'Tuyệt' trong cung con cái?", logic: 'KIDS_HURDLE_TUYET' },
        { text: "Con cái có năng khiếu về hội họa, phối màu không?", logic: 'KIDS_FUTURE_PAINT' },
        { text: "Tôi có số được con cái bảo vệ danh dự, uy tín?", logic: 'KIDS_LUCK_HONOR' },
        { text: "Làm sao để kích hoạt cung Tử Tức đang bị triệt?", logic: 'KIDS_ACTION_ACTIVATE' },
        { text: "Con cái có vượng vận nhờ việc tôi đổi hướng bàn làm việc?", logic: 'KIDS_FENGSHUI_DESK' },
        { text: "Tại sao con cái tôi thường có xu hướng thích phiêu lưu?", logic: 'KIDS_NATURE_ADVENTURE' },
        { text: "Tôi có số được con cái chăm sóc tận tình lúc lâm bệnh?", logic: 'KIDS_LATE_LIFE_SICK' },
        { text: "Hậu vận của tôi có thực sự viên mãn nhờ phúc đức của con?", logic: 'KIDS_END_LIFE_JOY' }
    ],
    colleagues: [
        { text: "Tôi thường gặp thuận lợi hay khó khăn với đồng nghiệp?", logic: 'COL_NATURE_RELATION' },
        { text: "Có kẻ tiểu nhân nào đang ngấm ngầm hãm hại tôi không?", logic: 'COL_HURDLE_SMALL_PEOPLE' },
        { text: "Làm sao để cải thiện mối quan hệ với cấp trên?", logic: 'COL_ACTION_SUPERIOR' },
        { text: "Đồng nghiệp có phải là những người hỗ trợ tôi tốt không?", logic: 'COL_NATURE_SUPPORT' },
        { text: "Tôi nên làm việc nhóm hay làm việc độc lập thì tốt hơn?", logic: 'COL_ACTION_METHOD' },
        { text: "Lá số của tôi có dấu hiệu của việc bị bạn bè phản bội không?", logic: 'COL_HURDLE_BETRAY' },
        { text: "Tôi có số làm 'sếp' được nhân viên nể phục không?", logic: 'COL_BOSS_POTENTIAL' },
        { text: "Màu sắc vật phẩm phong thủy nào giúp hóa giải thị phi?", logic: 'COL_FENGSHUI_COLOR' },
        { text: "Tại sao tôi thường bị hiểu lầm trong giao tiếp tại sở làm?", logic: 'COL_HURDLE_GOSSIP' },
        { text: "Tôi có nên chia sẻ bí mật kinh doanh với đồng nghiệp?", logic: 'COL_ACTION_SECRET' },
        { text: "Quý nhân của tôi trong môi trường làm việc là ai?", logic: 'COL_NOBLE_IDENTIFY' },
        { text: "Cung Nô Bộc (mở rộng) của tôi vượng hay suy?", logic: 'COL_PALACE_STRENGTH' },
        { text: "Làm sao để thu hút những người tài năng về đội của mình?", logic: 'COL_ACTION_RECRUIT' },
        { text: "Tôi có hợp với việc làm trong các tổ chức phi lợi nhuận?", logic: 'COL_ORGANIZATION_TYPE' },
        { text: "Những mâu thuẫn hiện tại sẽ kết thúc vào lúc nào?", logic: 'COL_TIMING_RESOLVE' },
        { text: "Tôi có nên tin tưởng hoàn toàn vào người cộng sự?", logic: 'COL_ACTION_TRUST' },
        { text: "Đồng nghiệp nam hay nữ sẽ hỗ trợ tôi đắc lực hơn?", logic: 'COL_GENDER_DYNAMICS' },
        { text: "Làm sao để xây dựng uy tín với những người xung quanh?", logic: 'COL_ACTION_REPUTATION' },
        { text: "Tôi có năng lực lãnh đạo bẩm sinh không?", logic: 'COL_LEADERSHIP' },
        { text: "Môi trường làm việc năng động có hợp với tôi không?", logic: 'COL_ENV_DYNAMICS' },
        { text: "Lá số có 'Tỷ Kiên' gây ra sự cạnh tranh quá mức không?", logic: 'COL_STARS_TY_KIEN' },
        { text: "Làm sao để hóa giải hạn 'Thị Phi' nơi công sở?", logic: 'COL_ACTION_GOSSIP' },
        { text: "Tôi có nên tham gia vào các hội nhóm, hiệp hội ngành nghề?", logic: 'COL_ACTION_NETWORKING' },
        { text: "Sự xuất hiện của 'Quan Sát' có làm tôi bị chèn ép không?", logic: 'COL_STARS_QUAN_SAT' },
        { text: "Làm sao để xoay chuyển tình thế khi bị sếp không tin tưởng?", logic: 'COL_ACTION_TURNAROUND' },
        { text: "Tôi có duyên với các mối quan hệ xã giao rộng rãi không?", logic: 'COL_NATURE_SOCIAL' },
        { text: "Việc đi công tác có giúp tôi mở rộng mạng lưới quan hệ?", logic: 'COL_ACTION_BUSINESS_TRIP' },
        { text: "Lá số có thần sát 'Quốc Ấn' giúp tăng uy danh không?", logic: 'COL_STARS_QUOC_AN' },
        { text: "Tôi có nên đề phòng những lời nịnh nọt của nhân viên?", logic: 'COL_HURDLE_FLATTERY' },
        { text: "Làm sao để tìm được cộng sự tâm đầu ý hợp theo can chi?", logic: 'COL_ACTION_FIND_PARTNER' },
        { text: "Nên làm gì khi đồng nghiệp vô tình tiết lộ bí mật của mình?", logic: 'COL_ACTION_SECRET_LEAK' },
        { text: "Tôi có duyên với việc làm việc trong các công ty gia đình?", logic: 'COL_TYPE_FAMILY' },
        { text: "Làm sao để duy trì sự chuyên nghiệp khi có nảy sinh tình cảm nơi sở làm?", logic: 'COL_ACTION_ROMANCE' },
        { text: "Tôi có số được đồng nghiệp cũ giới thiệu công việc tốt?", logic: 'COL_LUCK_EX_REF' },
        { text: "Tại sao tôi thường cảm thấy lạc lõng trong các buổi tiệc công ty?", logic: 'COL_PSYCHOLOGY_LONELY' },
        { text: "Làm sao để đối phó với những đồng nghiệp hay 'đâm sau lưng'?", logic: 'COL_HURDLE_BACKSTAB' },
        { text: "Tôi có duyên với người làm trong ngành ngoại giao không?", logic: 'COL_PARTNER_DIPLOMAT' },
        { text: "Vận trình quan hệ đồng nghiệp có vượng hơn vào mùa hạ?", logic: 'COL_TIMING_SUMMER' },
        { text: "Tôi nên sử dụng vật phẩm phong thủy gì trên bàn làm việc để hút quý nhân?", logic: 'COL_FENGSHUI_DESK_NOBLE' },
        { text: "Tôi có số trở thành 'trọng tài' giải quyết mâu thuẫn trong nhóm?", logic: 'COL_BOSS_MEDIATOR' },
        { text: "Làm sao để xây dựng văn hóa làm việc tích cực cho cấp dưới?", logic: 'COL_ACTION_CULTURE' },
        { text: "Tôi có duyên với việc làm việc trong các môi trường đa văn hóa?", logic: 'COL_ENV_MULTICULTURAL' },
        { text: "Vận trình quan điểm của sếp về tôi có thay đổi sau khi tôi lập công?", logic: 'COL_BOSS_VIEW' },
        { text: "Tôi nên chọn chỗ ngồi làm việc quay về hướng nào để tránh thị phi?", logic: 'COL_FENGSHUI_DESK_DIR' },
        { text: "Tôi có số được nhân viên trung thành tuyệt đối?", logic: 'COL_LUCK_LOYALTY' },
        { text: "Làm sao để hóa giải sự đố kỵ từ những người giỏi hơn mình?", logic: 'COL_HURDLE_ENVY' },
        { text: "Tôi có duyên với việc làm việc cho các tổ chức quốc tế?", logic: 'COL_TYPE_GLOBAL' },
        { text: "Vận trình quan hệ với đồng nghiệp vượng lên sau khi đổi chỗ ngồi?", logic: 'COL_LOCATION_MOVE' },
        { text: "Tại sao tôi thường gặp may mắn với những đồng nghiệp lớn tuổi?", logic: 'COL_LUCK_SENIOR' },
        { text: "Tôi có số phát đạt nhờ sự giúp đỡ của bạn bè ngoài ngành?", logic: 'COL_LUCK_OUTSIDER' },
        { text: "Làm sao để biết một đồng nghiệp là 'quý nhân' hay 'tiểu nhân'?", logic: 'COL_SIGNS_CHECK' },
        { text: "Sự xuất hiện của 'Tiết khí' có ảnh hưởng đến tâm trạng của đồng nghiệp?", logic: 'COL_ENV_SEASON' },
        { text: "Tôi có số được lãnh đạo ưu ái giao cho những trọng trách lớn?", logic: 'COL_LUCK_TASK' },
        { text: "Làm sao để duy trì sự cân bằng giữa tình cảm và công việc?", logic: 'COL_ACTION_BOUNDARY' },
        { text: "Tôi có duyên với việc làm việc trong các startup công nghệ?", logic: 'COL_TYPE_STARTUP' },
        { text: "Vận trình quan hệ xã hội của tôi có vượng hơn khi tham gia các hội thảo?", logic: 'COL_ACTION_EVENT' },
        { text: "Tôi nên dùng màu sắc gì cho trang phục công sở để tăng uy thế?", logic: 'COL_FENGSHUI_CLOTHES' },
        { text: "Tôi có số gặp được những cộng sự có cùng chí hướng?", logic: 'COL_LUCK_SOULMATE' },
        { text: "Làm sao để hóa giải hạn 'Kiếp Tài' trong các mối quan hệ?", logic: 'COL_STARS_REMEDY' },
        { text: "Tôi có duyên với ngành tư vấn nhân sự, săn đầu người?", logic: 'COL_SECTOR_HR' },
        { text: "Vận trình quan hệ với cấp trên có bị cản bởi 'Tuế Phá'?", logic: 'COL_HURDLE_TUE_PHA' },
        { text: "Tôi có số được cộng đồng ghi nhận công lao?", logic: 'COL_LUCK_RECOGNITION' },
        { text: "Làm sao để biết một nhân viên đang có ý định nhảy việc?", logic: 'COL_SIGNS_LEAVE' },
        { text: "Tôi có duyên với ngành truyền thông, quan hệ công chúng?", logic: 'COL_SECTOR_PR' },
        { text: "Vận trình quan hệ đồng nghiệp có vượng hơn vào ban ngày?", logic: 'COL_TIME_DAY' },
        { text: "Tại sao tôi thường bị thu hút bởi những sếp có tính cách nghiêm khắc?", logic: 'COL_BOSS_STRICT' },
        { text: "Tôi có số phát tài nhờ việc kết giao với giới thượng lưu?", logic: 'COL_LUCK_ELITE' },
        { text: "Làm sao để hóa giải sự trì trệ của cả đội ngũ?", logic: 'COL_ACTION_MOMENTUM' },
        { text: "Tôi có duyên với việc làm việc trong ngành du lịch, khách sạn?", logic: 'COL_SECTOR_HOSPITALITY' },
        { text: "Vận trình quan hệ xã hội của tôi vượng lên sau khi đổi số điện thoại?", logic: 'COL_FENGSHUI_PHONE' },
        { text: "Tại sao tôi thường gặp khó khăn khi làm việc với phụ nữ?", logic: 'COL_GENDER_FEMALE' },
        { text: "Tôi có số được quý nhân giúp đỡ thoát khỏi những scandal nơi công sở?", logic: 'COL_LUCK_SCANDAL' },
        { text: "Làm sao để tìm được người kế vị xứng đáng?", logic: 'COL_ACTION_SUCCESSION' },
        { text: "Tôi có duyên với ngành tổ chức sự kiện, tiệc tùng?", logic: 'COL_SECTOR_EVENT' },
        { text: "Vận trình quan hệ đồng nghiệp có vượng hơn khi đi về phương Tây?", logic: 'COL_LOCATION_WEST' },
        { text: "Tại sao tôi thường bị stress vì những lời đồn thổi vô căn cứ?", logic: 'COL_PSYCHOLOGY_STRESS' },
        { text: "Tôi có số phát đạt nhờ việc sở hữu mạng lưới quan hệ rộng khắp?", logic: 'COL_LUCK_NETWORK' },
        { text: "Làm sao để hóa giải sát khí từ hướng cửa chính phòng làm việc?", logic: 'COL_FENGSHUI_DOOR' },
        { text: "Tôi có duyên với ngành giáo dục, đào tạo doanh nghiệp?", logic: 'COL_SECTOR_TRAINING' },
        { text: "Vận trình quan hệ với sếp vượng lên sau mỗi kỳ nghỉ lễ?", logic: 'COL_TIMING_HOLIDAY' },
        { text: "Tại sao tôi thường gặp may mắn khi làm việc với nam giới?", logic: 'COL_GENDER_MALE' },
        { text: "Tôi có số được đồng nghiệp ngưỡng mộ như một thần tượng?", logic: 'COL_LUCK_IDOL' },
        { text: "Làm sao để xây dựng đội ngũ làm việc từ xa hiệu quả?", logic: 'COL_ACTION_REMOTE' },
        { text: "Tôi có duyên với ngành luật, tư vấn pháp lý cho doanh nghiệp?", logic: 'COL_SECTOR_LEGAL' },
        { text: "Vận trình quan hệ xã hội của tôi có bị ảnh hưởng bởi hướng bàn thờ?", logic: 'COL_FENGSHUI_ALTAR' },
        { text: "Tại sao tôi thường bị thu hút bởi những cộng sự có cá tính mạnh?", logic: 'COL_PARTNER_STRONG' },
        { text: "Tôi có số phát đạt nhờ việc tham gia vào các hiệp hội doanh nhân?", logic: 'COL_LUCK_ASSOCIATION' },
        { text: "Làm sao để hóa giải sự chia rẽ trong nội bộ công ty?", logic: 'COL_ACTION_UNITY' },
        { text: "Tôi có duyên với ngành bảo hiểm, quản trị rủi ro con người?", logic: 'COL_SECTOR_INSURANCE' },
        { text: "Vận trình quan hệ đồng nghiệp vượng lên khi tôi sử dụng nước hoa?", logic: 'COL_FENGSHUI_SCENT' },
        { text: "Tại sao tôi thường gặp khó khăn khi làm việc với người ít tuổi hơn?", logic: 'COL_AGE_JUNIOR' },
        { text: "Tôi có số được đồng nghiệp giúp đỡ hoàn thành dự án khó?", logic: 'COL_LUCK_PROJECT' },
        { text: "Làm sao để tạo động lực cho nhân viên khi công ty gặp khó khăn?", logic: 'COL_ACTION_MOTIVATE' },
        { text: "Tôi có duyên với ngành tâm lý học hành vi tổ chức?", logic: 'COL_SECTOR_PSYCH' },
        { text: "Vận trình quan hệ xã hội của tôi vượng lên sau khi đổi kiểu tóc?", logic: 'COL_FENGSHUI_HAIR' },
        { text: "Tại sao tôi thường bị thu hút bởi những môi trường làm việc yên tĩnh?", logic: 'COL_ENV_SILENT' },
        { text: "Tôi có số phát đạt nhờ việc làm đại diện cho tiếng nói của nhân viên?", logic: 'COL_LUCK_VOICE' },
        { text: "Làm sao để hóa giải sự cạnh tranh không lành mạnh từ đối thủ?", logic: 'COL_ACTION_RIVAL' },
        { text: "Tôi có duyên với ngành công nghiệp phần mềm sáng tạo?", logic: 'COL_SECTOR_SOFTWARE' },
        { text: "Hậu vận của tôi có được hưởng sự kính trọng từ các thế hệ đàn em?", logic: 'COL_LATE_LIFE_RESPECT' }
    ],
    partnership: [
        { text: "Tôi có hợp với việc hùn hạp làm ăn không?", logic: 'PARTNER_NATURE_TRUST' },
        { text: "Người đối tác như thế nào sẽ mang lại thành công cho tôi?", logic: 'PARTNER_TYPE_IDEAL' },
        { text: "Năm nay có phải là thời điểm tốt để ký kết hợp đồng lớn?", logic: 'PARTNER_TIMING_CONTRACT' },
        { text: "Tôi có số bị đối tác lừa gạt hay chiếm dụng vốn không?", logic: 'PARTNER_HURDLE_FRAUD' },
        { text: "Làm sao để hóa giải mâu thuẫn trong việc phân chia lợi nhuận?", logic: 'PARTNER_ACTION_PROFIT' },
        { text: "Tôi nên chọn đối tác mang hành gì để tương sinh?", logic: 'PARTNER_ELEMENT_COMPAT' },
        { text: "Việc hợp tác kinh doanh có giúp tôi mở rộng quy mô không?", logic: 'PARTNER_ACTION_EXPAND' },
        { text: "Lá số của tôi có 'Quý Nhân' trợ giúp trong việc ký kết không?", logic: 'PARTNER_NOBLE_STARS' },
        { text: "Tại sao các mối quan hệ hợp tác của tôi thường đứt gánh giữa đường?", logic: 'PARTNER_HURDLE_END' },
        { text: "Tôi có nên đưa người thân vào làm chung công ty không?", logic: 'PARTNER_ACTION_FAMILY' },
        { text: "Bản mệnh của tôi phù hợp với việc làm chủ một mình hay có cộng sự?", logic: 'PARTNER_SOLO_VS_TEAM' },
        { text: "Làm sao để nhận biết một đối tác đang có ý định rút lui?", logic: 'PARTNER_SIGNS_LEAVE' },
        { text: "Tôi có duyên với các hợp đồng từ chính phủ hay tổ chức lớn?", logic: 'PARTNER_TYPE_GOV' },
        { text: "Hợp tác với người nước ngoài có mang lại vận may cho tôi không?", logic: 'PARTNER_TYPE_FOREIGN' },
        { text: "Tài lộc từ việc hợp tác sẽ vượng nhất vào tháng nào?", logic: 'PARTNER_TIMING_MONTH' },
        { text: "Tôi có nên nhường quyền quyết định cho đối tác không?", logic: 'PARTNER_ACTION_POWER' },
        { text: "Làm sao để bảo vệ uy tín của thương hiệu khi hợp tác?", logic: 'PARTNER_ACTION_REPUTATION' },
        { text: "Tôi có duyên với việc nhượng quyền thương mại (Franchise)?", logic: 'PARTNER_TYPE_FRANCHISE' },
        { text: "Sự xuất hiện của 'Tỷ Kiên' có gây ra tranh chấp cổ phần không?", logic: 'PARTNER_STARS_SHARE' },
        { text: "Hậu vận của tôi có được hưởng lợi từ những mối quan hệ hợp tác lâu dài?", logic: 'PARTNER_LATE_LIFE' },
        { text: "Tôi có số gặp được 'tri kỷ' trong kinh doanh không?", logic: 'PARTNER_LUCK_SOULMATE' },
        { text: "Làm sao để hóa giải vận đen khi đối tác gặp nạn?", logic: 'PARTNER_ACTION_LUCK_FIX' },
        { text: "Tôi có duyên với việc tham gia vào các liên minh chiến lược?", logic: 'PARTNER_TYPE_ALLIANCE' },
        { text: "Vận trình hợp tác của tôi có vượng hơn khi đi về phương Nam?", logic: 'PARTNER_LOCATION_SOUTH' },
        { text: "Nên sử dụng vật phẩm phong thủy gì để kích hoạt vận may ký kết?", logic: 'PARTNER_FENGSHUI_SIGN' },
        { text: "Tôi có số trở thành nhà đầu tư thiên thần cho các dự án khởi nghiệp?", logic: 'PARTNER_TYPE_ANGEL' },
        { text: "Làm sao để xây dựng lòng trung thành ở các đối tác chiến lược?", logic: 'PARTNER_ACTION_LOYALTY' },
        { text: "Tôi có duyên với việc làm việc trong các tập đoàn đa quốc gia?", logic: 'PARTNER_TYPE_MNC' },
        { text: "Vận trình hợp tác của tôi có vượng lên sau khi đổi văn phòng?", logic: 'PARTNER_LOCATION_MOVE' },
        { text: "Tại sao tôi thường gặp may mắn với những đối tác trẻ tuổi?", logic: 'PARTNER_LUCK_YOUTH' },
        { text: "Tôi có số phát đạt nhờ việc mua lại các công ty đang gặp khó khăn?", logic: 'PARTNER_TYPE_M_A' },
        { text: "Làm sao để biết một bản hợp đồng là 'bẫy' pháp lý?", logic: 'PARTNER_SIGNS_TRAP' },
        { text: "Sự xuất hiện của 'Tiết khí' có ảnh hưởng đến quyết định của đối tác?", logic: 'PARTNER_ENV_SEASON' },
        { text: "Tôi có số được các tổ chức tài chính lớn rót vốn đầu tư?", logic: 'PARTNER_LUCK_FUNDING' },
        { text: "Làm sao để duy trì sự minh bạch trong quản lý tài chính chung?", logic: 'PARTNER_ACTION_FINANCE' },
        { text: "Tôi có duyên với việc làm việc trong các startup kỳ lân?", logic: 'PARTNER_TYPE_UNICORN' },
        { text: "Vận trình hợp tác của tôi vượng lên khi tôi tham gia các hội chợ thương mại?", logic: 'PARTNER_ACTION_FAIR' },
        { text: "Tôi nên dùng màu sắc gì cho bản thuyết trình để thuyết phục đối tác?", logic: 'PARTNER_FENGSHUI_PITCH' },
        { text: "Tôi có số gặp được những đối tác có tiềm lực tài chính hùng mạnh?", logic: 'PARTNER_LUCK_POWER' },
        { text: "Làm sao để hóa giải sự bất đồng về triết lý kinh doanh?", logic: 'PARTNER_ACTION_VISION' },
        { text: "Tôi có duyên với ngành tư vấn sáp nhập, chuyển nhượng doanh nghiệp?", logic: 'PARTNER_SECTOR_MA' },
        { text: "Vận trình hợp tác với cấp dưới có bị cản bởi 'Tuế Phá'?", logic: 'PARTNER_HURDLE_TUE_PHA' },
        { text: "Tôi có số được cộng đồng doanh nhân tôn vinh?", logic: 'PARTNER_LUCK_FAME' },
        { text: "Làm sao để biết đối tác đang có hành vi gian lận?", logic: 'PARTNER_SIGNS_FRAUD' },
        { text: "Tôi có duyên với ngành truyền thông, tiếp thị xã hội?", logic: 'PARTNER_SECTOR_SOCIAL' },
        { text: "Vận trình hợp tác vượng hơn khi tôi làm việc vào ban ngày?", logic: 'PARTNER_TIME_DAY' },
        { text: "Tại sao tôi thường bị thu hút bởi những đối tác có phong thái tự tin?", logic: 'PARTNER_NATURE_ATTR' },
        { text: "Tôi có số phát tài nhờ việc kết giao với giới chính trị?", logic: 'PARTNER_LUCK_POLITIC' },
        { text: "Làm sao để hóa giải sự cạnh tranh từ chính những người cùng đội?", logic: 'PARTNER_HURDLE_INTERNAL' },
        { text: "Tôi có duyên với việc làm việc trong ngành xuất nhập khẩu?", logic: 'PARTNER_SECTOR_EXIM' },
        { text: "Vận trình hợp tác xã hội vượng lên sau khi đổi website công ty?", logic: 'PARTNER_FENGSHUI_WEB' },
        { text: "Tại sao tôi thường gặp khó khăn khi hợp tác với người cùng tuổi?", logic: 'PARTNER_AGE_SAME' },
        { text: "Tôi có số được quý nhân giúp đỡ thoát khỏi những vụ kiện tụng kinh tế?", logic: 'PARTNER_LUCK_LEGAL' },
        { text: "Làm sao để tìm được người đồng sáng lập lý tưởng?", logic: 'PARTNER_ACTION_COFOUNDER' },
        { text: "Tôi có duyên với ngành tổ chức hội nghị, hội thảo doanh nhân?", logic: 'PARTNER_SECTOR_CONFERENCE' },
        { text: "Vận trình hợp tác vượng hơn khi đi về phương Tây?", logic: 'PARTNER_LOCATION_WEST' },
        { text: "Tại sao tôi thường bị stress vì những cam kết không được thực hiện?", logic: 'PARTNER_PSYCHOLOGY_STRESS' },
        { text: "Tôi có số phát đạt nhờ việc nắm giữ bí mật kinh doanh của đối tác?", logic: 'PARTNER_LUCK_INSIDER' },
        { text: "Làm sao để hóa giải sát khí từ hướng cửa văn phòng đối tác?", logic: 'PARTNER_FENGSHUI_DOOR_DIR' },
        { text: "Tôi có duyên với ngành giáo dục, tư vấn du học?", logic: 'PARTNER_SECTOR_STUDY_ABROAD' },
        { text: "Vận trình hợp tác với sếp vượng lên sau mỗi dự án thành công?", logic: 'PARTNER_TIMING_PROJECT' },
        { text: "Tại sao tôi thường gặp may mắn khi làm việc với người khác phái?", logic: 'PARTNER_GENDER_DYNAMICS' },
        { text: "Tôi có số được đối tác ngưỡng mộ như một chuyên gia?", logic: 'PARTNER_LUCK_EXPERT' },
        { text: "Làm sao để xây dựng mối quan hệ đối tác dựa trên niềm tin?", logic: 'PARTNER_ACTION_TRUST_BUILD' },
        { text: "Tôi có duyên với ngành luật, tư vấn sở hữu trí tuệ?", logic: 'PARTNER_SECTOR_IP' },
        { text: "Vận trình hợp tác xã hội có bị ảnh hưởng bởi hướng bàn làm việc?", logic: 'PARTNER_FENGSHUI_DESK' },
        { text: "Tại sao tôi thường bị thu hút bởi những đối tác có tư duy đột phá?", logic: 'PARTNER_NATURE_INNOVATION' },
        { text: "Tôi có số phát đạt nhờ việc tham gia vào các diễn đàn kinh tế toàn cầu?", logic: 'PARTNER_LUCK_FORUM' },
        { text: "Làm sao để hóa giải sự nghi ngờ trong nội bộ liên doanh?", logic: 'PARTNER_ACTION_DOUBT' },
        { text: "Tôi có duyên với ngành bảo hiểm, quản trị rủi ro doanh nghiệp?", logic: 'PARTNER_SECTOR_RISK' },
        { text: "Vận trình hợp tác vượng lên khi tôi sử dụng vật phẩm bằng đồng?", logic: 'PARTNER_FENGSHUI_METAL' },
        { text: "Tại sao tôi thường gặp khó khăn khi hợp tác với người mệnh Hỏa?", logic: 'PARTNER_ELEMENT_FIRE' },
        { text: "Tôi có số được đối tác giúp đỡ vượt qua những cơn khủng hoảng?", logic: 'PARTNER_LUCK_CRISIS' },
        { text: "Làm sao để tạo động lực cho đối tác khi dự án bị đình trệ?", logic: 'PARTNER_ACTION_MOTIVATE' },
        { text: "Tôi có duyên với ngành tâm lý học đàm phán?", logic: 'PARTNER_SECTOR_NEGOTIATE' },
        { text: "Vận trình hợp tác xã hội vượng lên sau khi đổi logo công ty?", logic: 'PARTNER_FENGSHUI_LOGO' },
        { text: "Tại sao tôi thường bị thu hút bởi những môi trường làm việc cởi mở?", logic: 'PARTNER_ENV_OPEN' },
        { text: "Tôi có số phát đạt nhờ việc làm cầu nối cho các thương vụ lớn?", logic: 'PARTNER_LUCK_BRIDGE' },
        { text: "Làm sao để hóa giải sự cạnh tranh từ các công ty vệ tinh?", logic: 'PARTNER_ACTION_COMPETITION' },
        { text: "Tôi có duyên với ngành công nghiệp phần mềm ứng dụng?", logic: 'PARTNER_SECTOR_APP' },
        { text: "Vận trình hợp tác vượng hơn vào mùa xuân?", logic: 'PARTNER_TIMING_SPRING' },
        { text: "Tại sao tôi thường gặp may mắn khi hợp tác với người mệnh Mộc?", logic: 'PARTNER_ELEMENT_WOOD' },
        { text: "Tôi có số được đối tác cũ mời quay lại hợp tác?", logic: 'PARTNER_LUCK_RETURN' },
        { text: "Làm sao để xây dựng văn hóa hợp tác bền vững?", logic: 'PARTNER_ACTION_CULTURE' },
        { text: "Tôi có duyên với ngành công nghiệp sáng tạo nội dung?", logic: 'PARTNER_SECTOR_CONTENT' },
        { text: "Vận trình hợp tác xã hội vượng lên khi tôi tham gia các khóa học?", logic: 'PARTNER_ACTION_LEARN' },
        { text: "Tại sao tôi thường bị thu hút bởi những đối tác có tầm nhìn xa?", logic: 'PARTNER_NATURE_VISION' },
        { text: "Tôi có số phát đạt nhờ việc nắm giữ các cổ phần ưu đãi?", logic: 'PARTNER_LUCK_STOCK' },
        { text: "Làm sao để hóa giải sự mâu thuẫn giữa các thành viên hội đồng?", logic: 'PARTNER_ACTION_BOARD' },
        { text: "Tôi có duyên với ngành bất động sản khu công nghiệp?", logic: 'PARTNER_SECTOR_RE_IZ' },
        { text: "Vận trình hợp tác vượng lên khi tôi đi công tác nước ngoài?", logic: 'PARTNER_ACTION_TRAVEL' },
        { text: "Tại sao tôi thường gặp khó khăn khi hợp tác với người mệnh Thổ?", logic: 'PARTNER_ELEMENT_EARTH' },
        { text: "Tôi có số được đối tác nhường lợi ích trong các thương vụ khó?", logic: 'PARTNER_LUCK_CONCEDE' },
        { text: "Làm sao để tạo niềm tin với các nhà đầu tư mạo hiểm?", logic: 'PARTNER_ACTION_VC_TRUST' },
        { text: "Tôi có duyên với ngành tư vấn chiến lược doanh nghiệp?", logic: 'PARTNER_SECTOR_STRATEGY' },
        { text: "Vận trình hợp tác xã hội vượng lên sau khi tôi đổi xe?", logic: 'PARTNER_FENGSHUI_CAR' },
        { text: "Tại sao tôi thường bị thu hút bởi những đối tác có tính kỷ luật?", logic: 'PARTNER_NATURE_DISCIPLINE' },
        { text: "Tôi có số phát đạt nhờ việc kết nghĩa anh em với đối tác?", logic: 'PARTNER_LUCK_BROTHER' },
        { text: "Làm sao để hóa giải sự can thiệp từ người thân của đối tác?", logic: 'PARTNER_HURDLE_FAMILY' },
        { text: "Hậu vận của tôi có được hưởng sự thành đạt từ các liên minh cũ?", logic: 'PARTNER_END_LIFE_JOY' }
    ],
    misfortune: [
        { text: "Trong đời tôi cần đề phòng những đại hạn nào?", logic: 'MIS_NATURE_MAJOR_LIMIT' },
        { text: "Làm sao để hóa giải hạn 'Tam Tai' hay 'Thái Tuế'?", logic: 'MIS_ACTION_TAM_TAI' },
        { text: "Tôi có gặp nguy hiểm về sông nước hay lửa không?", logic: 'MIS_TYPE_ELEMENTAL' },
        { text: "Năm nay tôi có hạn về pháp luật hay kiện cáo không?", logic: 'MIS_YEARLY_LEGAL' },
        { text: "Cách đức năng thắng số áp dụng như thế nào cho tôi?", logic: 'MIS_PHILOSOPHY_MORAL' },
        { text: "Những giấc mơ có báo hiệu gì về tai ương sắp tới?", logic: 'MIS_SIGNS_DREAMS' },
        { text: "Tôi có nên thực hiện các lễ cúng giải hạn không?", logic: 'MIS_ACTION_CEREMONY' },
        { text: "Lá số có chứa các thần sát 'Thiên La', 'Địa Võng' không?", logic: 'MIS_STARS_LA_VONG' },
        { text: "Làm sao để tâm an giữa những biến động của vận mệnh?", logic: 'MIS_PSYCHOLOGY' },
        { text: "Tôi có gặp hạn mất của hay bị trộm cướp không?", logic: 'MIS_TYPE_THEFT' },
        { text: "Việc chuyển chỗ ở có giúp tôi thoát khỏi vận xui?", logic: 'MIS_ACTION_MOVE' },
        { text: "Những người xung quanh có mang lại rắc rối cho tôi không?", logic: 'MIS_HURDLE_OTHERS' },
        { text: "Làm sao để tăng cường 'Hộ Thân Phù' qua Bát tự?", logic: 'MIS_ACTION_PROTECT' },
        { text: "Tôi nên đề phòng tai nạn giao thông vào mùa nào?", logic: 'MIS_TIMING_TRAVEL' },
        { text: "Lỗi lầm trong quá khứ có đang ảnh hưởng đến hiện tại?", logic: 'MIS_KARMA' },
        { text: "Làm sao để biến thách thức thành cơ hội đổi đời?", logic: 'MIS_ACTION_TRANSFORM' },
        { text: "Tôi có được sự bảo trợ của 'Thần Hộ Mệnh' không?", logic: 'MIS_PROTECTION' },
        { text: "Tại sao vận rủi thường đến vào lúc tôi đang thành công?", logic: 'MIS_PEAK_RISK' },
        { text: "Sức mạnh nội tại của tôi nằm ở đâu để vượt qua khó khăn?", logic: 'MIS_INTERNAL_STRENGTH' },
        { text: "Sau cơn mưa trời sẽ sáng, khi nào là lúc tôi thoát hạn?", logic: 'MIS_TIMING_END' },
        { text: "Hạn 'Tuế Sát' có đang làm trì trệ cuộc sống của tôi?", logic: 'MIS_STARS_TUE_SAT' },
        { text: "Làm sao để hóa giải 'Vong Thần' gây ra sự bất an?", logic: 'MIS_ACTION_VONG_THAN' },
        { text: "Tôi có số gặp đại nạn nhưng được cứu thoát thần kỳ?", logic: 'MIS_NATURE_MIRACLE' },
        { text: "Những năm nào mang can chi gì thường là 'điểm đen' của tôi?", logic: 'MIS_TIMING_BLACK_DOT' },
        { text: "Làm sao để nhận biết và tránh xa những nguồn năng lượng xấu?", logic: 'MIS_ACTION_ENERGY' },
        { text: "Tôi có nên làm các việc đại sự trong tháng cô hồn không?", logic: 'MIS_ACTION_GHOST_MONTH' },
        { text: "Việc thay đổi tên có giúp tôi cải vận thoát khổ không?", logic: 'MIS_ACTION_RENAME' },
        { text: "Lá số có 'Tang Môn', 'Điếu Khách' chủ về tin buồn không?", logic: 'MIS_STARS_TANG_MON' },
        { text: "Làm sao để xây dựng tâm thái vững vàng trước nghịch cảnh?", logic: 'MIS_ACTION_MINDSET' },
        { text: "Tôi có hạn về hỏa hoạn hay điện giật trong năm nay không?", logic: 'MIS_TYPE_FIRE_ELEC' },
        { text: "Làm sao để hóa giải hạn 'Kình Dương' chủ về hình thương?", logic: 'MIS_STARS_KINH_DUONG' },
        { text: "Tôi có duyên với việc hồi phục sau những cú sốc lớn?", logic: 'MIS_NATURE_RECOVERY' },
        { text: "Vận xui có vượng hơn khi tôi tiếp xúc với người mệnh Hỏa?", logic: 'MIS_ELEMENT_FIRE' },
        { text: "Tại sao tôi thường gặp rắc rối vào những ngày mưa gió?", logic: 'MIS_ENV_WEATHER' },
        { text: "Tôi có số thoát được những vụ kiện tụng oan sai?", logic: 'MIS_LUCK_LEGAL_WIN' },
        { text: "Làm sao để bảo vệ tài sản trước nguy cơ bị lừa đảo?", logic: 'MIS_ACTION_FRAUD_PROT' },
        { text: "Tôi có duyên với việc giúp đỡ người khác vượt qua hoạn nạn?", logic: 'MIS_TYPE_HELPER' },
        { text: "Vận trình rủi ro có vượng hơn khi tôi đi về phương Nam?", logic: 'MIS_LOCATION_SOUTH' },
        { text: "Nên sử dụng vật phẩm phong thủy gì để đeo bên mình khi đi xa?", logic: 'MIS_FENGSHUI_AMULET' },
        { text: "Tôi có số gặp đại nạn nhưng được 'Mã Tinh' hóa giải?", logic: 'MIS_STARS_MA_TINH' },
        { text: "Làm sao để tâm lý không bị gục ngã trước những mất mát?", logic: 'MIS_PSYCH_LOOS' },
        { text: "Tôi có duyên với việc nghiên cứu các phương pháp giải hạn?", logic: 'MIS_SECTOR_RESEARCH' },
        { text: "Vận trình rủi ro vượng lên sau khi tôi thay đổi nơi ở?", logic: 'MIS_LOCATION_MOVE' },
        { text: "Tại sao tôi thường gặp may mắn trong những tình huống nguy kịch?", logic: 'MIS_LUCK_CRITICAL' },
        { text: "Tôi có số trở thành 'người sống sót' duy nhất trong một vụ tai nạn?", logic: 'MIS_NATURE_SURVIVOR' },
        { text: "Làm sao để nhận biết các điềm báo từ thiên nhiên?", logic: 'MIS_SIGNS_NATURE' },
        { text: "Tôi nên làm gì khi gặp hạn 'La Võng' cản trở?", logic: 'MIS_STARS_REMEDY' },
        { text: "Sự xuất hiện của 'Tiết khí' có làm tăng rủi ro cho tôi?", logic: 'MIS_ENV_SEASON' },
        { text: "Tôi có số được tổ tiên che chở vượt qua mọi tai vạ?", logic: 'MIS_LUCK_ANCESTOR' },
        { text: "Làm sao để duy trì sự tỉnh táo khi đứng trước hiểm nguy?", logic: 'MIS_ACTION_ALERT' },
        { text: "Tôi có duyên với việc tham gia các khóa học cứu hộ?", logic: 'MIS_ACTION_RESCUE' },
        { text: "Vận trình rủi ro có vượng hơn khi tôi đi máy bay?", logic: 'MIS_TYPE_FLIGHT' },
        { text: "Nên trồng cây gì trước cửa nhà để ngăn chặn sát khí?", logic: 'MIS_FENGSHUI_PLANT' },
        { text: "Tôi có số gặp đại nạn nhưng được thú cưng cứu mạng?", logic: 'MIS_LUCK_PET' },
        { text: "Làm sao để hóa giải năng lượng xấu từ đám tang?", logic: 'MIS_ACTION_CLEANSE' },
        { text: "Tôi có duyên với việc giúp người khác cải vận?", logic: 'MIS_TYPE_REFORMER' },
        { text: "Vận trình rủi ro có vượng hơn vào ban đêm?", logic: 'MIS_TIME_NIGHT' },
        { text: "Tại sao tôi thường bị thu hút bởi những nơi có địa khí xấu?", logic: 'MIS_NATURE_MAGNET' },
        { text: "Tôi có số phát tài sau mỗi lần gặp đại hạn lớn?", logic: 'MIS_LUCK_AFTER_RESET' },
        { text: "Làm sao để hóa giải sự ám hại từ những kẻ giấu mặt?", logic: 'MIS_HURDLE_SECRET_ENEMY' },
        { text: "Tôi có duyên với ngành bảo hiểm tình nguyện không?", logic: 'MIS_SECTOR_INSURANCE' },
        { text: "Vận trình rủi ro vượng lên sau khi tôi phá bỏ công trình cũ?", logic: 'MIS_ACTION_DEMOLISH' },
        { text: "Tại sao tôi thường gặp rắc rối vào những tháng mùa đông?", logic: 'MIS_SEASON_WINTER' },
        { text: "Tôi có số được quý nhân bảo hộ về mặt tâm linh?", logic: 'MIS_LUCK_SPIRITUAL' },
        { text: "Làm sao để tìm được nơi trú ẩn an toàn theo phong thủy?", logic: 'MIS_FENGSHUI_SHELTER' },
        { text: "Tôi có duyên với việc nghiên cứu y học pháp y không?", logic: 'MIS_SECTOR_FORENSIC' },
        { text: "Vận trình rủi ro vượng lên sau mỗi lần tôi thay đổi công việc?", logic: 'MIS_CAREER_IMPACT' },
        { text: "Tại sao tôi thường gặp may mắn khi đi du lịch đường thủy?", logic: 'MIS_TYPE_WATER_TRAVEL' },
        { text: "Tôi có số thoát được những vụ bắt giữ trái phép?", logic: 'MIS_LUCK_DETENTION' },
        { text: "Làm sao để bảo vệ danh dự trước những lời cáo buộc sai trái?", logic: 'MIS_ACTION_DEFEND' },
        { text: "Tôi có duyên với ngành quản lý thảm họa quốc gia?", logic: 'MIS_SECTOR_MANAGEMENT' },
        { text: "Vận trình rủi ro vượng lên khi tôi sử dụng màu sắc không hợp mệnh?", logic: 'MIS_FENGSHUI_COLOR' },
        { text: "Tại sao tôi thường cảm thấy bất an trước mỗi chuyến đi xa?", logic: 'MIS_PSYCHOLOGY_TRAVEL' },
        { text: "Tôi có số gặp đại nạn nhưng được người lạ cứu giúp?", logic: 'MIS_LUCK_STRANGER' },
        { text: "Làm sao để hóa giải sát khí từ công trình xây dựng bên cạnh?", logic: 'MIS_FENGSHUI_CONSTR' },
        { text: "Tôi có duyên với ngành tư vấn an toàn lao động?", logic: 'MIS_SECTOR_SAFETY' },
        { text: "Vận trình rủi ro vượng lên sau khi tôi làm lễ chuyển dời ban thờ?", logic: 'MIS_ACTION_ALTAR_MOVE' },
        { text: "Tại sao tôi thường gặp khó khăn khi làm việc với người mang hành Kim?", logic: 'MIS_ELEMENT_METAL' },
        { text: "Tôi có số thoát được những vụ tai nạn tập thể thần kỳ?", logic: 'MIS_LUCK_MASS' },
        { text: "Làm sao để thu hút những năng lượng bình an vào nhà?", logic: 'MIS_ACTION_ZEN' },
        { text: "Tôi có duyên với ngành nghiên cứu về hiện tượng siêu nhiên?", logic: 'MIS_SECTOR_PARANORMAL' },
        { text: "Vận trình rủi ro vượng lên khi tôi để phòng ngủ quá tối?", logic: 'MIS_FENGSHUI_LIGHT' },
        { text: "Tại sao tôi thường gặp may mắn khi đi về hướng Tây Bắc?", logic: 'MIS_LOCATION_NW' },
        { text: "Tôi có số phát lộc sau khi vượt qua bạo bệnh?", logic: 'MIS_LUCK_HEALTH' },
        { text: "Làm sao để hóa giải vận đen từ những vật phẩm cũ?", logic: 'MIS_ACTION_OLD_ITEM' },
        { text: "Tôi có duyên với việc tham gia các hoạt động nhân đạo?", logic: 'MIS_ACTION_HUMANITY' },
        { text: "Vận trình rủi ro vượng lên sau mỗi lần tôi thay đổi kiểu tóc?", logic: 'MIS_FENGSHUI_STYLE' },
        { text: "Tại sao tôi thường gặp rắc rối vào những ngày trăng khuyết?", logic: 'MIS_TIMING_MOON' },
        { text: "Tôi có số được các đấng bậc bề trên bảo vệ?", logic: 'MIS_LUCK_HIGH' },
        { text: "Làm sao để chọn được trang sức hộ mệnh theo Bát tự?", logic: 'MIS_ACTION_JEWELRY' },
        { text: "Tôi có duyên với ngành chữa lành tâm linh, thôi miên?", logic: 'MIS_SECTOR_HEALING' },
        { text: "Vận trình rủi vượng lên khi tôi đặt gương đối diện giường ngủ?", logic: 'MIS_FENGSHUI_MIRROR' },
        { text: "Tại sao tôi thường gặp khó khăn tiền bạc mỗi khi gặp vận hạn?", logic: 'MIS_WEALTH_SYNC' },
        { text: "Tôi có số vượt qua được những thảm họa tự nhiên lớn?", logic: 'MIS_LUCK_NATURAL' },
        { text: "Làm sao để duy trì sự cân bằng ngũ hành trong môi trường sống?", logic: 'MIS_ACTION_BALANCE' },
        { text: "Tôi có duyên với việc ghi chép lại những trải nghiệm cận tử?", logic: 'MIS_SECTOR_NDE' },
        { text: "Vận trình rủi ro vượng lên sau khi tôi đổi số tài khoản ngân hàng?", logic: 'MIS_ACTION_FINANCE' },
        { text: "Tại sao tôi thường bị thu hút bởi những bộ phim kinh dị, trinh thám?", logic: 'MIS_PSYCHOLOGY_DARK' },
        { text: "Tôi có số được con cháu phù hộ, cứu thoát tai ương khi về già?", logic: 'MIS_LATE_LIFE_LUCK' },
        { text: "Hậu vận của tôi có thực sự thoát khỏi mọi kiếp nạn trần gian?", logic: 'MIS_END_LIFE_FREEDOM' }
    ],
};

const QUESTIONS = {};
THEMES.forEach(theme => {
    const rawData = QUESTIONS_DATA[theme.id] || [];
    QUESTIONS[theme.id] = rawData.map((item, idx) => ({
        id: `${theme.id}_${idx + 1}`,
        text: item.text,
        logic: item.logic
    }));
});

module.exports = { THEMES, QUESTIONS };
